### ISSUE TITLE
OptifineHD侵权问题

### ISSUE THREAD

**Issue by dong031001** [TCreopargh/GreedyCraft#1]
OptifineHD作者很明确在发布页面指出除非拥有特别授权，所有整合包都不应将OptifineHD附在其中。
https://www.optifine.net/faq

> Can I include OptiFine in my modpack?
Generally no, unless you have an explicit permission from us.

**Comment by dong031001** [comment]
顺便一提，整合包中450余模组除OptifineHD外应也有部分模组开源协议和使用许可不支持第二方再分发源代码和/或二进制Jar文件。建议使用manifest.json替代所有模组二进制文件。

**Comment by TCreopargh** [comment]
optifine目前是依靠启动器安装的，整合包内应该是不含optifine的本体文件的，只含有配置文件（如果确实有本体文件请告诉我，我会想法处理）
模组的问题主要是基于国内访问curseforge的速度决定，之后该整合包正式发布到curse时会基于curseforge的打包方式。另外据我所知没有安装明面上不允许用于整合包的mod（之前有个幸运方块发现后被我删了）

**Comment by dong031001** [comment]
> optifine目前是依靠启动器安装的，整合包内应该是不含optifine的本体文件的，只含有配置文件（如果确实有本体文件请告诉我，我会想法处理）
> 模组的问题主要是基于国内访问curseforge的速度决定，之后该整合包正式发布到curse时会基于curseforge的打包方式。另外据我所知没有安装明面上不允许用于整合包的mod（之前有个幸运方块发现后被我删了）

无论是否是启动器安装，OptifineHD都不允许将其加入任何整合包内（除非有特别授权）。如果有玩过国外的整合包，应该可以发现它们都有一个共同点：不附带任何形式的OptifineHD。

**Comment by TCreopargh** [comment]
> > optifine目前是依靠启动器安装的，整合包内应该是不含optifine的本体文件的，只含有配置文件（如果确实有本体文件请告诉我，我会想法处理）
> > 模组的问题主要是基于国内访问curseforge的速度决定，之后该整合包正式发布到curse时会基于curseforge的打包方式。另外据我所知没有安装明面上不允许用于整合包的mod（之前有个幸运方块发现后被我删了）
> 
> 无论是否是启动器安装，OptifineHD都不允许将其加入任何整合包内（除非有特别授权）。如果有玩过国外的整合包，应该可以发现它们都有一个共同点：不附带任何形式的OptifineHD。

那这个应该是启动器的问题，这个包只是通过配置文件告诉启动器让它自己安装optifine，跟我放一个提醒玩家自己安装optifine的大标题没有本质上的区别。（这个包由于mod数量过多并且非常依赖optifine，就算有安装optifine的指示也会有大部分玩家嫌麻烦/不会装而不去安装。启动器只是自动化了这一过程而已。）
另外这个包目前只是国内测试阶段，正式发布到curse时是不带optifine的。
