### ISSUE TITLE
[BUG]Travel Anchors doesn't work if there is a wall in front of Travel Anchor.

### ISSUE THREAD

**Issue by AxolotlAccount** [TCreopargh/GreedyCraft#101]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
 - [ x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Travel Anchors doesn't render behind blocks.

**To Reproduce**
Place a Travel Anchor behind blocks with width of 3 or more, you won't be able to teleport to it with Staff of Traveling.

**Expected behavior**
You should be able to teleport to Travel Anchors behind blocks.

**Screenshots**
https://imgur.com/a/M1Yn355

**Crash reports or logs**
https://paste.ubuntu.com/p/vNsgHKjdvR/

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.30.1.107.1 )
Did you add or remove mods? ( No )
Did you edit any config or script? ( No )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( No Shader )
Singleplayer, LAN game or server pack? ( Singleplayer )

**Additional context**
Adding Travel Anchor tile-entity (enderio:tile_travel_anchor) to the skipHiddedTileEntityRenderingBlacklist (Entity Culling config) fixes the issue.

**Comment by TCreopargh** [comment]
Thanks for the report, will add the fix in next version

**Comment by TCreopargh** [comment]
Fixed in 1.31.0
