### ISSUE TITLE
[BUG] 多个回城药水使用后消耗1个 其余全部消失

### ISSUE THREAD

**Issue by KamenriderZO** [TCreopargh/GreedyCraft#102]
手持物品21个回城药水使用后消耗了1个，回家后可以看到物品栏有1空瓶
其他20个全没了，没有空瓶（排除了快速连续使用）。

版本：最新国际版

**Comment by TCreopargh** [comment]
请确保没有添加增加堆叠数量之类的mod

**Comment by KamenriderZO** [comment]
抱歉。。。找到了那20瓶药水在Rustic的榨汁桶里。。。回程的时候估计右键按着一回去直接放桶里没找到
