### ISSUE TITLE
[BUG] Ur-ghast despawning

### ISSUE THREAD

**Issue by TealSeer** [TCreopargh/GreedyCraft#104]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [X] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Ur-ghast boss despawns upon reaching certain y height above tower dungeon in twilight forest

**To Reproduce**
1. Go to twilight forest ur ghast tower
2. Trigger ur ghast spawn
3. While fighting ur ghast, if he paths up towards a certain y level (which he frequently does, there's no way to stop this), he despawns and you are unable to complete the boss fight

**Expected behavior**
I expected to kill the ur-ghast and continue progression

**Screenshots**
If applicable, add screenshots to help explain your problem. (N/A)

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder. (N/A)

**Details**
Please fill out the blanks below:
Modpack Version: (1.30.1.107.1)
Did you add or remove mods? (No)
Did you edit any config or script? (No)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default)
Singleplayer, LAN game or server pack? (Singleplayer)

**Additional context**

**Comment by TCreopargh** [comment]
You can find another ur ghast by exploring so you can progress forward, I'll look into the issue

**Comment by TCreopargh** [comment]
Should be fixed in 1.31.0
