### ISSUE TITLE
[BUG] Sakura Ume Leaf Crash Persisting

### ISSUE THREAD

**Issue by TealSeer** [TCreopargh/GreedyCraft#105]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [X] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
The game crashes back to the main menu with an exception related to Sakura's Ume tree leaves. I believe this is the crash that was warned about in the 1.31.0.109.1 changelog, but it's happened now more than once. 

**To Reproduce**
1. Have a world generated from version 1.30.1.107.1 or earlier
2. Update to 1.31.0.109.1 and bring your world save over to the new version
3. Load the world
4. This part is not completely cut and dry because the crash happened both times after about 5 - 10 minutes of playing. From what I can discern from the logs though it's triggered when a Ume Tree from Sakura either attempts to grow from sapling to full tree, or when the leaves on it begin to decay (can't tell which).
5. Admire the shutting down internal server screen as the game crashes

**Expected behavior**
The crash should have only happened once after I loaded the old save, and then never again.

**Screenshots**
N/A

**Crash reports or logs**
https://pastebin.com/raw/G06Yyz4x

**Details**
Please fill out the blanks below:
Modpack Version: (1.31.0.109.1)
Did you add or remove mods? (No)
Did you edit any config or script? (No)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default)
Singleplayer, LAN game or server pack? (Singleplayer)

**Additional context**
N/A

**Comment by TCreopargh** [comment]
Looks like the only fix is updating but I can no longer include newer versions in the pack. As a temporary fix, you can move MMLib and Sakura from the old version into the new version. If you want it to be compatible with further versions try to find all ume trees and chop them down.

**Comment by TCreopargh** [comment]
Also try just deleting Sakura from the pack, enter the world, and reinstall it. It will delete all Sakura related items and blocks, which may make some parts of your world look bad but it can fix the problem.
