### ISSUE TITLE
[BUG] incorrect biome/terrain gen when generating new chunks with Chunk Pregenerator

### ISSUE THREAD

**Issue by Stormelon** [TCreopargh/GreedyCraft#109]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
When using Chunk-Pregenerator to generate new chunks in a world, those new chunks have bizarre biome/terrain generation compared to normal terrain/biome generation for that seed. The resulting chunks consist almost entirely of Plains, often with terrain expected for other biomes.

**To Reproduce**
1. Load or create a world, preferably a new one, with permission to use all /pregen commands
2. use any one of the "/pregen gen" commands to generate new terrain. (for example, "/pregen gen startradius square 0 0 64 0" in a new world to generate new terrain in a 64 chunk radius about the world origin.
3. Wait until most of the task is done.
4. Explore the newly generated terrain. Notice that most of it is plains, often with inappropriate terrain features such as mountains and sand.

**Expected behavior**
Exploring the same areas manually on the same seed creates the expected variation in biomes, terrain in structures.

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![2021-02-11_15 15 11](https://user-images.githubusercontent.com/38019915/107711411-7505f000-6c7c-11eb-9f1d-73afaeedf42a.png)
This was made by running Chunk-pregenerator with the command I mentioned above. Note that regions surrounding the spawn region consist almost entirely of plains. Note how this "plains" contains inappropriate terrain features like sand, stone, and snow.

**Crash reports or logs**
This issue doesn't cause crashes.

**Details**
Please fill out the blanks below:
Modpack Version: (1.31.0)
Did you add or remove mods? (No)
Did you edit any config or script? (No)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default)
Singleplayer, LAN game or server pack? (Singleplayer) Note: this issue occurs when Chunk-Pregenerator runs on a dedicated server as well.

**Additional context**
If it helps, i've done some research into this issue and some say that this is caused by an interaction with JustEnoughIDs, due to the fact that mod changes the chunk format and how certain information, (specifically changing data types for tracking biomes) are stored in the region file. If that is the culprit, then I don't know if it is possible for you to fix it on your side.

**Comment by TCreopargh** [comment]
If it's not working, I wonder if removing the chunk pregenerator is a good solution, because no one seems to be using it anyway

**Comment by TCreopargh** [comment]
Chunk pregenerator is removed
