### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yyado** [TCreopargh/GreedyCraft#110]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：
 * Java版本：
 * 分配的内存：
 * 物理内存：
 * 是否增减了mod：
 * 是否修改了材质包：
 * 是否修改了魔改/配置文件：
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
¿

**Comment by yyado** [comment]
1.31.0.109版本 炫钢熔炉制作炫钢只能加催化之星才会产出炫钢锭，否则无论是否加其他催化剂，成品都会直接消失，材料一样会被扣除。
还有神秘6的揭示之护目镜，第一次打开游戏的时候，会消失在饰品栏中，点击空位可以拿出来，再放回去又消失，只能小退一次游戏才会恢复正常

**Comment by TCreopargh** [comment]
1.之前测试过没有此类问题，建议换个地方重建下机器并且设置足够多的输入/输出口
2.老问题了，无法修复

**Comment by yyado** [comment]
我只放了两个能源输入 其余方块一侧都是输入另一侧全是输出，而且第一次消耗了我6份材料之后回档又试了一次还是那样，在创造档试出来加催化之星才行，回到自己的生存档加了催化之星产出了炫钢锭，等下我把机器搬走再试一次不加催化之星
