### ISSUE TITLE
[BUG]FTB主体以及其组件彻底奔溃的BUG。

### ISSUE THREAD

**Issue by adminr-001** [TCreopargh/GreedyCraft#113]
此错误发生时间：2021年2月13日11:35
最近一次正常使用时间：2021年2月12日11:32
运行环境：win10-1909专业版/14G内存/i7九代/GTX 1650（系统/使用内存/处理器/显卡）
出现此次错误的可能原因：今天第一次打开存档后出现一个“是/否选项”，内容好像有FTB字样（未截图），我点了否，然后所有存档均不可用，所有备份均不可用，新建存档均不可用，无法正常加载世界（所有存档直接奔溃进入以下界面）：
![BT%_PC~W D H7BUATREM6AE](https://user-images.githubusercontent.com/78994199/107841429-b968cb80-6df5-11eb-8a63-51931e5c20e7.png)
附奔溃报告：
[Uploading crash-2021-02-13_12.00.34-server.txt…]()

**Comment by TCreopargh** [comment]
请重新安装游戏
