### ISSUE TITLE
[Suggestion] Zenscript usage permission question?

### ISSUE THREAD

**Issue by mindcloud69** [TCreopargh/GreedyCraft#118]
I am developing my own modpack for a small group of friends and family, and your scripts for GreedyCraft are among the best I have ever seen. I have been learning from them and I would like to be able to use sections from them. 

   I was wondering if you would allow this as long as I attributed where and from whom I got the sections I use by adding a link in the file and on my mod pack description?

Thank you in advance whatever you answer is! I have learned a lot from your project.

**Comment by TCreopargh** [comment]
Yes, if you add links and credits in your script you can use part of my scripts.

**Comment by mindcloud69** [comment]
Thank you very much, and I really like what you have done with this modpack!
