### ISSUE TITLE
[BUG] 无底之箱无法拾取物品

### ISSUE THREAD

**Issue by zhao1348298823** [TCreopargh/GreedyCraft#12]
## 请在下面详细描述你遇到的Bug

更新到1.15.0后，“无底之箱“ 不能自动吸取掉落物到箱子里面了，他会直接进背包而不是箱子

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.15.0
 * Java版本：8
 * 分配的内存：10240MB
 * 物理内存：16GB
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：

**Comment by TCreopargh** [comment]
你可能使用了AE无线终端+磁卡或者其他的帮助拾取的物品，请脱下所有盔甲、饰品，清空物品栏只保留无底之箱再试，如果问题解决请close，如果没解决请回复

**Comment by TCreopargh** [comment]
由于太长时间没有回复暂时关闭，如果看到了请告知
