### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChewiestAbyss9** [TCreopargh/GreedyCraft#120]
This started just today, after I tried (and failed) to update to 1.32, and then later reverted to the previous version of 1.31.109.1. Whenever I try to launch the game, when it would normally go to the main menu it just brings the crash screen up with no idea what was crashing it, and also saying that it may have been caused by out of date java (which I have redownloaded and tried again to no change, version jre 1.8.0_281) or that there is not enough allocated ram (I already have 20 GB allocated), so I have no idea what the problem is, in the crash report it says that it may be because of optifine, but I have played this modpack with the same version and with optifine just the day before and it worked fine.

**To Reproduce**
No idea what would be different from normal other than just using ATlauncher instead of MultiMC

**Expected behavior**
When launching, goes through all the loading, but after finishing just goes to the crashscreen

**Crash reports or logs**
https://pastebin.com/JvR3s8z4

**Details**
Modpack Version: (1.31.109.1 + 1.32)
Did you add or remove mods? (none)
Did you edit any config or script? (real first person, shoulder surf, better foliage/grass (I forget what the name is) and OreExcavation integration were all disabled from config, memory cleaner had auto clean turned off)
Using shaders? (no)
Singleplayer, LAN game or server pack? (singleplayer)

**Additional context**
Using ATlauncher rather than MultiMC

**Comment by TCreopargh** [comment]
How did you update? If you just unzip the modpack and copy its files then paste on your instance folder it doesn't work, try a clean reinstall.

**Comment by ChewiestAbyss9** [comment]
ATlauncher has a feature where it can automatically take the zip file from CurseForge and update the pack itself

**Comment by TCreopargh** [comment]
Please install the new version as a new instance and manually move the save files. The auto update might not work with this pack, especially if an update deletes some files
