### ISSUE TITLE
[BUG] 暮色森林跑图路上崩溃，重进存档和重启游戏都进不去存档

### ISSUE THREAD

**Issue by SaltedFisherSF** [TCreopargh/GreedyCraft#121]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述 

在暮色跑图路上游戏崩溃，重新进入存档马上又崩溃，

### 如果你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
https://paste.ubuntu.com/p/gwmmFJzgfH/
https://paste.ubuntu.com/p/DWN3wrhCc6/
https://paste.ubuntu.com/p/VVp9P9STs9/
第一条是首次崩溃，第二条是重进存档崩溃，第三条是重启游戏崩溃

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 暮色跑图，两三天前也出现过，但不是这个版本整合，之前直接重启游戏，然后进存档了，这次进不去存档了
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：GreedyCraft-1.32.0.111.0
 * Java版本：1.8.0-281
 * 分配的内存：16384MB
 * 物理内存：32GB
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：没开光影
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：R5-3600/RTX2080S
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：GreedyCraft-1.30.1.107.0
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法 
Xaeros_Minimap_21.3.0.2_Forge_1.12 禁用此模组后成功进入存档

**Comment by akasia** [comment]
也是遇到同样的问题

**Comment by SaltedFisherSF** [comment]
我上面写错了，Optifine有的，安装新版本整合包后进游戏默认没开光影，我还以为没有，实际Opti有的

**Comment by TCreopargh** [comment]
已修复
