### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by mqy2005605** [TCreopargh/GreedyCraft#122]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
一进入暮色森林米诺菇的地牢就崩档，然后就进不去了，只能调取没进去时的备份

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

[crash-2021-02-19_17.45.16-client.txt](https://github.com/TCreopargh/GreedyCraft/files/6009423/crash-2021-02-19_17.45.16-client.txt)

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 进入地牢就会重现
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.32.0.111.0
 * Java版本：64位最新
 * 分配的内存：10240
 * 物理内存：16312
 * 是否增减了mod：没
 * 是否修改了材质包：没
 * 是否修改了魔改/配置文件：没
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.32.0.111.0
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
请将Xaero's minimap回退到旧版本，已经向地图作者反应该问题

**Comment by mqy2005605** [comment]
怎么退回旧版本呀

**Comment by TCreopargh** [comment]
去curseforge上下

**Comment by mqy2005605** [comment]
无法下载
那个作者给的链接失效了

**Comment by mqy2005605** [comment]
http://bit.ly/2M7DYbU
这个失效了

**Comment by TCreopargh** [comment]
？我让你去curseforge下载
