### ISSUE TITLE
[BUG] Server crashing "Xaero's Minimap"

### ISSUE THREAD

**Issue by KyleW512** [TCreopargh/GreedyCraft#123]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Loading into the server shuts down, giving me a crash report saying "Xaero's Minimap".
**To Reproduce**
1. Load into a server, and it may crash with the prompt of "Xaero's Minimap"
**Expected behavior**
Jumping into the minoshroom dungeon the server crashed.
**Screenshots**
https://gyazo.com/669533aa4cc7f23f9ff651af3fbe4bda
**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

**Details**
Please fill out the blanks below:
Modpack Version: (1.32.0.111.1  )
Did you add or remove mods? (No  )
Did you edit any config or script? (No  )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default  )
Singleplayer, LAN game or server pack? ( Singleplayer )

**Additional context**

**Comment by TCreopargh** [comment]
Please go to xaero's minimap in mod settings and turn off entity radar.
This will be fixed in next update.

**Comment by TCreopargh** [comment]
Fixed in latest version
