### ISSUE TITLE
[BUG] Reproducable "Waiting for server..." when entering world

### ISSUE THREAD

**Issue by eeriely** [TCreopargh/GreedyCraft#124]
- [ x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Really love the pack so far and would like to continue playing, but after entering the world I only get "Waiting for server..." in The One Probe overlay. Nothing is usable. Waited over 20 minutes, nothing changed. Tried it like 10 times.

**To Reproduce**
1. entering the world is enough that it happens

**Crash reports or logs**
I attached a zip with 6 stall reports and the latest.log
[LogAndStallReports.zip](https://github.com/TCreopargh/GreedyCraft/files/6014297/LogAndStallReports.zip)

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.32.0.111.1 )
Did you add or remove mods? ( no )
Did you edit any config or script? ( no )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( Default )
Singleplayer, LAN game or server pack? ( Singleplayer )

**Additional context**
System info:
Intel Core i7-10700K
GeForce RTX 3070
64 GB RAM
Java 1.8.0_281
I'm using GDLauncher with recommended JVM arguments and allocated 16.384MB RAM, but also tried MultiMC, no difference
World is Default Preset (BoP)
I already unlocked the nether and was about to build a Durasteel Forge.
Base is nothing crazy: 7 Hopping Bonsai Pots, 7 Actually Additions Farmers, 28 Arboreal Extractors, 2 Fractionating Stills, 3 Compression Dynamos, 1 Steam Dynamo, some Solar Panels, Atomic Reconstructor with Lens of the Miner and some other machines, that are not running and a Tinkers Smeltery automated with hopper and Redstone Clock making Modularium ingots. 
I think the last thing I did before the problem started was start making modularium in my tinkers forge, but not 100% sure.

[link to world download 189.9MB](https://mega.nz/file/q01BjYBQ#bZaONg5LXxinJooge04rRSAdklLEA6emiMQ8PN5uyas)
my basecamp is at 347 66 126
I added the world download because the problem is at least for me 100% reproducable, which might help finding the problem easier than only the logs. Don't know if you really have time to check it, if not that's fine too :).

Greetings
eeriely

**Comment by TCreopargh** [comment]
Try to restore a backup that is made before when this problem happens, I'll look into this later

**Comment by eeriely** [comment]
I restored a backup, made the Modularium and built the Durasteel Forge, played for an hour and no issues so far, I don't think I did anything different but who knows :)

**Comment by TCreopargh** [comment]
I've looked at the stall reports and it looks like a specific zombie is causing all of the problem. Since this is a duplication of #54, I'm closing this, if you encounter the problem again please try to use the emergency item (can be claimed in quest menu) to clear all mobs.

**Comment by eeriely** [comment]
Thank you for the fast responses, I will try the emergency item if it happens again.
