### ISSUE TITLE
Typo in JEI [BUG]

### ISSUE THREAD

**Issue by gat0king** [TCreopargh/GreedyCraft#126]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [X ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Molten Netherite from Content Tweaker is spelled wrong in JEI
**To Reproduce**
1. Search JEI for Molten Netherite or anything that leads to the liquid
2. See that its misspelled

**Expected behavior**
For the block to be spelled Netherite

**Screenshots**
[Screenshot](https://imgur.com/XEfV6T2)

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.32.0.111.1 )
Did you add or remove mods? (No  )
Did you edit any config or script? ( No )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( Default )
Singleplayer, LAN game or server pack? ( Singleplayer )

**Additional context**
Not an important problem but I thought you would want to fix it.

**Comment by TCreopargh** [comment]
Fixed in 1.33
