### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gageabr** [TCreopargh/GreedyCraft#127]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

**Details**
Please fill out the blanks below:
Modpack Version: (  )
Did you add or remove mods? (  )
Did you edit any config or script? (  )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (  )
Singleplayer, LAN game or server pack? (  )

**Additional context**

**Comment by gageabr** [comment]
I am trying to make a crucible for Thaumcraft and it won’t work I am doing exactly what I’m asked I have watched many videos but it still doesn’t work this may or may not be a bug. I cannot progress any further without the item

**Comment by TCreopargh** [comment]
There's no bug here, you are doing wrong, right click a cauldron with salis mundus. It requires research progress, you must right click a bookshelf with salis mundus first

**Comment by gageabr** [comment]
Okay thank you sorry, erm while I have you I’m having trouble with the durasteel forge I have set it all up and put items in that it tells me too but it still says no input item what do I have to do? I have tried to google it and can’t find anything

**Comment by TCreopargh** [comment]
Add more item input and output hatch, it must be large enough to contain all possible input/outputs

**Comment by gageabr** [comment]
I have two of each plus everything else it tells me to have but it still says missing input item It has power I don’t know what else to do

**Comment by TCreopargh** [comment]
Try to upgrade them instead of adding more

**Comment by gageabr** [comment]
I don’t mean to be a pain but they are upgraded any further upgrades need durasteel and that’s what I’m trying to get it has two input two output for item one energy input and the rest liquid output (all upgraded about half way) as stated in the guide I have a reactor Dynamo powering it fully upgraded

**Comment by TCreopargh** [comment]
Have you put all of the needed items in it

**Comment by gageabr** [comment]
Does every single item on the blueprint for durasteel have to be in there? Because about three of them are locked I figured it was those materials that made it so a hand full of them would be okay I don’t know how I can make anymore progress without durasteel

**Comment by TCreopargh** [comment]
The last recipe in JEI is the minimum requirement, all other recipes add catalysts.

**Comment by gageabr** [comment]
Okay... thanks

**Comment by gageabr** [comment]
I started a creative game build the exact set up put in every single item on the durasteel jei and it still says missing input item

**Comment by TCreopargh** [comment]
Use bigger input/output hatches and make sure you have energy input

**Comment by TCreopargh** [comment]
Also make sure you didn't put your items into the output hatch, someone made this mistake before

**Comment by gageabr** [comment]
I have my durasteel forge powered with some very over the top setup and it gets to around 70% then tells me I’m missing input item when it was originally working

**Comment by TCreopargh** [comment]
Try to move your entire multiblock and make sure it isn't riding the edge of chunks, modular machinery is kinda buggy

**Comment by gageabr** [comment]
I need durasteel to move on with skilled engineer and it’s broken 😂I’ve moved it twice I’ve Chuck loaded it I’ve restarted it I’ve made new components tried different power sorted different recipes I’m sorry for bugging you but I cannot move on without it

**Comment by gageabr** [comment]
I am so so sorry for wasting your time for some reason I had a hidden item output and amongst my enormous energy set up I didn’t see it and the durasteel was hiding in there 😂I just destroyed the whole thing again to move once more and it came out the hatch thank you for your time and patience with me! By the way great pack absolutely insane

**Comment by gageabr** [comment]
One more thing I can build the builder but there is not a recipe for the shape card I need for it?

**Comment by TCreopargh** [comment]
iirc builder is disabled

**Comment by gageabr** [comment]
Oh okay, so I’ve build a solid centrifuge and I can only get netherack and permafrost to work it doesn’t take cobblestone sand gravel or leaves?

**Comment by gageabr** [comment]
Another issue I’m having is I need to enter the dreadlands but the ritual will not start I have been into the task pages and it has the question mark but won’t tell me what I need to get so I’ve looked around it looks like I need to kill the wither which I cannot do without entering dreadlands so I’m not sure if it’s bugged or not but it seems like I keep trying to progress but everywhere I turn it’s locked behind a game stage that I can’t seem to get. I need to kill Valkyrie with a bravery certificate or kill her and get one? But I have already killed her in the aether

**Comment by VeikkoV** [comment]
you can kill the wither once you have used the awakened eye. crafting it needs you to kill the wastelands boss aswell as gaia guard

**Comment by gageabr** [comment]
Okay thank you didn’t see that anywhere so I was a bit confused, do you know what the issue with the solid centrifuge is? It doesn’t take half of the material it says it does like cobblestone stone dirt sand?

**Comment by TCreopargh** [comment]
Use bigger input/output hatches

**Comment by gageabr** [comment]
I have both reinforced input output with 12 slots for each I have multiple fluid input Hatches the system works with netherack, leaves, logs and Ice but doesn’t seem to take much else

**Comment by TCreopargh** [comment]
Try to add more output slots, they must be enough to contain all possible outputs

**Comment by gageabr** [comment]
How do I achieve master engineer I have looked and cannot find it, also thaumcraft is really not my strong suit I’ve watched video after video and i still don’t even understand the research part do I have to do this to progress?

**Comment by TCreopargh** [comment]
Do mekanism quests 
You should join the discord for such discussions
