### ISSUE TITLE
[BUG] Looking up the opinium core from Extra Utils 2 causes a crash to title

### ISSUE THREAD

**Issue by Pleshie** [TCreopargh/GreedyCraft#129]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Looked up "ring" in jei and scrolled through the pages a bit and I crashed. Re-entering the world and opening up your inventory immediately crashes you. Crash report said something about a inspiring opinium core and made a new world and looked up "opinium" in JEI and the same thing happened as soon as I typed the 3rd letter.

**To Reproduce**
1. Make a new world. Mine was completely default.
2. Open up your inventory and start typing "opinium core" into the JEI search bar. You'll crash when you type in the first i

**Expected behavior**
For the opinium cores to show up and not crash the game

**Screenshots**
N/A

**Crash reports or logs**
https://paste.ubuntu.com/p/hxTkcBT38W/

**Details**
Please fill out the blanks below:
Modpack Version: ( GreedyCraft-1.32.0.111.1 )
Did you add or remove mods? (No )
Did you edit any config or script? (No)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (No)
Singleplayer, LAN game or server pack? (Singleplayer)

**Additional context**
N/A

**Comment by TCreopargh** [comment]
Doesnt happen for me, try to restart your game
