### ISSUE TITLE
[BUG] 阶段与任务重置（续）

### ISSUE THREAD

**Issue by zjh790** [TCreopargh/GreedyCraft#13]
前一个被关闭的问题的回答：https://paste.ubuntu.com/p/xW7NyHfSjH/

**Comment by TCreopargh** [comment]
你提交的东西不对，请仔细看下然后重新提交，这是某个mod的配置文件不是崩溃报告

崩溃报告文件位于整合包内**.minecraft\versions\GreedyCraft\crash-reports**文件夹，文件名为发生崩溃时的日期和时间。

**Comment by TCreopargh** [comment]
看错了，我以为你是上一个崩溃了没发崩溃报告的

**Comment by TCreopargh** [comment]
请检查下UUID在你更新版本前后是否改变，如果没有变却任务没了的话我也不知道为啥。

**Comment by zjh790** [comment]
漂亮，完全没变

**Comment by zjh790** [comment]
啊对了，跟新后我一上来就得先让我组队什么的，但是以前没有

**Comment by TCreopargh** [comment]
emm那这个就属于玄学问题了，不过能回档解决

**Comment by TCreopargh** [comment]
对了你有没有改过玩家名字

**Comment by zjh790** [comment]
没有

**Comment by zjh790** [comment]
这样我上传一下老版本的需要吗？

**Comment by zjh790** [comment]
https://paste.ubuntu.com/p/69sZTQtqSR/

**Comment by TCreopargh** [comment]
无法确定问题，下次遇到的话建议回档。。因为能回档解决所以先关闭了
