### ISSUE TITLE
[BUG] Can't load a single player world or join multiplayer.

### ISSUE THREAD

**Issue by thenoobofthewest** [TCreopargh/GreedyCraft#133]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
I click play on singleplayer - it says loading world then about 30 seconds later it says shutting down world.
on multiplayer it says: java.lang.nullpointerexception group
when loading.

**To Reproduce**
1. Go to single player click new or old world.
2. on multiplayer click join server
4. See error java.lang.nullpointerexception group

**Expected behavior**
I'd b able to log in.

**Screenshots**

**Crash reports or logs**
https://pastebin.com/kGrA0AnG

**Details**
Please fill out the blanks below:
Modpack Version: (1.33.0.112.1)
Did you add or remove mods? ( no )
Did you edit any config or script? ( no  )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( default  )
Singleplayer, LAN game or server pack? ( single/multiplayer )

**Additional context**

**Comment by TCreopargh** [comment]
I think this exists in vanilla, you need to restart the game

**Comment by thenoobofthewest** [comment]
Hi I've reinstalled multiple times and restarted the game/ my pc many times.

**Comment by TCreopargh** [comment]
After searching for it I think it's caused by your antivirus or firewall. Try to restart your computer, exit all antivirus softwares and have a try
