### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by grayggr** [TCreopargh/GreedyCraft#136]
Hi

Modpack was running perfectly until the Twilight Forest Xaero Minimap issue. Updated to new version of the modpack today - but now getting crashes to desktop. 

This was/is the crash report.

Any ideas - thanks.
[hs_err_pid9908.log](https://github.com/TCreopargh/GreedyCraft/files/6030843/hs_err_pid9908.log)

**Comment by TCreopargh** [comment]
The game ran out of memory. Try to allocate less ram and close all background processes
