### ISSUE TITLE
[BUG] Crash FTB Quests (ftbquests), FTB Library (ftblib), FastWorkbench (fastbench)

### ISSUE THREAD

**Issue by dbluegmc** [TCreopargh/GreedyCraft#137]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [ X] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Crashed upon loading save today, was working fine before. Was already on latest version 1.33.0.112.1

**To Reproduce**
Just tried to load save, immediate crash. Same thing happened with twilight forest bug, but was fixed last update, thanks.

**Expected behavior**

**Screenshots**

**Crash reports or logs**
https://paste.ubuntu.com/p/r6ZV7ZCDSf/

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.33.0.112.1 )
Did you add or remove mods? (  no)
Did you edit any config or script? ( no )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (  default)
Singleplayer, LAN game or server pack? (single  )

**Additional context**

**Comment by TCreopargh** [comment]
Restoring a backup should solve it
