### ISSUE TITLE
[BUG] 神秘研究全解

### ISSUE THREAD

**Issue by MAS-W** [TCreopargh/GreedyCraft#14]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
拿着装有任意源质的源质安瓿对着魔导鉴阅台（thaumadditions:thaumic_lectern）可以直接解开所有的研究

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 拿着装有任意源质的源质安瓿
2. 右键魔导鉴阅台
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.16.1（之前的某两个版本也可以，所以应该是一直存在）
 * Java版本：jre-8u271
 * 分配的内存：10GB
 * 物理内存：16GB
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.16.1
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法
ban掉魔导鉴阅台 反正这东西好像没什么用

**Comment by TCreopargh** [comment]
经测试问题存在，不过恐怕只能用禁用鉴阅台的方法暴力修复

**Comment by TCreopargh** [comment]
0f9f73058c4f4b6939f8d97a5f6dd95b8c6d6da0
