### ISSUE TITLE
[Suggestion] Add a quarry mod

### ISSUE THREAD

**Issue by Monniasza** [TCreopargh/GreedyCraft#143]
**Is your feature request related to a problem? Please describe.**
The modpack lacks a good quarry, so it is difficult to mine large amounts of resources

**Describe the solution you'd like**
Possible quarry mods:
- BuildCraft
- Simple Quarry
- MegaQuarry (requires balancing and probably hard mode)

**Describe alternatives you've considered**
RFTools quarry card, but that is too complex to set up

**Additional context**

**Comment by TCreopargh** [comment]
Use Quantum Quarry from random things, this is enough.
