### ISSUE TITLE
All gamestages lost after shutdown crash[BUG]

### ISSUE THREAD

**Issue by frechluemmel** [TCreopargh/GreedyCraft#145]
- [x] Yes, I'm sure this problem isn't because my game ran out of RAM. 

My Computer has shut down out of nowhere, now i lack every gamestage ever accomplished, maybe there is a way to restore them or edit the files so i can get my current gamestage back?

1. Let the pc instant shutdown without any known reason ;)
2. Start your game again
3. Join your world and notice the loss of all of your gamestages

**Expected behavior**
Not this

**Crash reports or logs**
No logs due to hard shutdown

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.31.0.109.1)
Did you add or remove mods? (no)
Did you edit any config or script? (no)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default)
Singleplayer, LAN game or server pack? (Singleplayer)

**Additional context**
Anyways, love your modpack, keep the work up buddy!

**Comment by TCreopargh** [comment]
This is a known problem with gamestages and can happen on any modpack that has gamestages in it, I can't do anything. When this happens just restore a backup (click "backups" in world selection menu)

**Comment by frechluemmel** [comment]
Unfortunately i tried that already and it didn´t work for me.

**Comment by TCreopargh** [comment]
Try restoring an earlier backup, it's likely that you restored a backup that's made after the problem occured
