### ISSUE TITLE
[BUG] Bird's Food皮塔饼和实用扩展面团合成冲突

### ISSUE THREAD

**Issue by FallDark** [TCreopargh/GreedyCraft#147]
## 描述你的想法或建议
![20210305214609](https://user-images.githubusercontent.com/25171639/110123861-64b8df00-7dfc-11eb-8127-3107b380067f.png)
![20210305214658](https://user-images.githubusercontent.com/25171639/110123865-6682a280-7dfc-11eb-8275-f42a0ecd8480.png)

虽然可以通过手动合成，但是在RFT自动合成机和TE循环装配机(TE显示有两种，但是不能锁定其中一种)里面默认是合成皮塔饼
## 你是否有实现该想法的方法或建议？如果有，请说明
删除皮塔饼用小麦合成方式，只留下面粉合成？

**Comment by TCreopargh** [comment]
1.34已更改
