### ISSUE TITLE
[BUG] 天地同寿和生命汲取效果无法发动

### ISSUE THREAD

**Issue by 1074143632** [TCreopargh/GreedyCraft#148]
大剑上有天地同寿和生命汲取词条，打怪物（盖亚、木桩等）时没有发动扣血或者回血效果，伤害也没有发生改变；
箭矢有天地同寿和暮色词条，打木桩时没有触发天地同寿扣血效果和暮色额外伤害效果；
在1.26.0版本时箭矢的天地同寿效果有发动。

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.33.1
 * Java版本：1.8.0_281
 * 分配的内存：10G
 * 物理内存：16G
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：改了星辉等级
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.26.0

**Comment by TCreopargh** [comment]
只是新版削了而已

**Comment by 1074143632** [comment]
是直接移除了效果吗？我这边一点触发效果的迹象都没有

**Comment by TCreopargh** [comment]
削的很厉害，而且只有很小概率触发
