### ISSUE TITLE
[Suggestion] 关于神秘时代的流程

### ISSUE THREAD

**Issue by MAS-W** [TCreopargh/GreedyCraft#15]
## 描述你的想法或建议
因为，神秘时代有很多研究并不是直接显示出来的，很多人跟着任务流程走也不知道接下来该做些什么
所以，能否再重置一下神秘的任务线

## 你是否有实现该想法的方法或建议？如果有，请说明
1.增加一些引导的任务或者在任务里增加一些说明（具体写在下面）
2.让不会的人自己去找教程（bushi）

## 还有什么别的内容想让我们知道吗？
> 关于悖论物质
悖论物质的研究前置为：咒波裂隙，vis电池，注魔
咒波裂隙的前置为咒波，咒波是不直接显示的，解锁方法为待在一个有大量咒波的区块内
vis电池的前置为结晶农场和充能基座，结晶农场的前置是矿石，矿石和结晶农场都是不直接显示的，矿石解锁需要扫描矿物，结晶农场的研究需要扫描野生的晶簇才能看见
所以，能否对这些增加一些任务或者说明

> 关于邪术学
深入研究邪术学的前置为发现神秘学和血腥仪式，血腥仪式的前置为血腥崇拜，这个也是不直接显示的，需要扫描血腥教徒解锁
所以，能否将血腥仪式的那个任务放入任务线以及增加任务或者说明

> 关于元始珍珠
最初的元始珍珠只能通过炸裂缝获得，但是最高的几率也只有17%（https://www.mcmod.cn/item/133720.html）
同样的，能否增加一些说明

还有稳定器也是

**Comment by TCreopargh** [comment]
感谢反馈，我会考虑一下。
另外任务重构目前较为麻烦（因为不同模式用的是不同的任务系统），一般会放到一个大版本里搞定

**Comment by MAS-W** [comment]
如果重做任务麻烦的话，能否考虑在某些地方增加一些说明，比如对应任务的界面，或者是说明书之类的

**Comment by TCreopargh** [comment]
0f9f73058c4f4b6939f8d97a5f6dd95b8c6d6da0
