### ISSUE TITLE
[BUG]Server crashes when player joins

### ISSUE THREAD

**Issue by Nitroxko** [TCreopargh/GreedyCraft#150]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Whenever I or anyone else join the server, it crashes. There is a good minute or two before the crash, during which you can play "normally". We tried clearing all entities, but the problem persists. I even tried playing the world in a single-player instance. I will upload that crash report

**To Reproduce**
1. Join world
2. Wait for crash

**Screenshots**

**Crash reports or logs**
https://pastebin.com/sEMf522K

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.33.1.113.1 )
Did you add or remove mods? ( No )
Did you edit any config or script? (No  )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( default )
Singleplayer, LAN game or server pack? ( singleplayer and server pack )

**Comment by TCreopargh** [comment]
Serene Tweaks is causing the problem, either remove this mod or create a new world

**Comment by Nitroxko** [comment]
Removed the mod and it's still crashing https://pastebin.com/TS30ZFwU

**Comment by TCreopargh** [comment]
Most probably because your world file is corrupted. Please restore a backup or start a new world.
