### ISSUE TITLE
[BUG] quest reset 

### ISSUE THREAD

**Issue by JacksonHuang1** [TCreopargh/GreedyCraft#152]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [ x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
I was doing thaumcraft things to get void seeds, and then I got a crash, something with xaero's. No biggie, I'll just rejoin. When I rejoined, all my quests were reset (but I kept my gamestages)except for the milestones ones. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.
https://drive.google.com/file/d/17amTIU3cCir-NZFwb5fEB2jjqSN7khtq/view?usp=sharing     (I couldn't paste it on pastebin, it was too long)
**Details** 
Please fill out the blanks below:
Modpack Version: ( latest  )
Did you add or remove mods? ( no )
Did you edit any config or script? (   no)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( default )
Singleplayer, LAN game or server pack? ( singleplayer )

**Additional context**
sometimes I get this weird waiting for server thing that forces me to kill the instance

**Comment by TCreopargh** [comment]
It's a hard crash, probably caused by insufficient memory
Anyways restore a backup if this happens
