### ISSUE TITLE
[BUG] 关于匠魂材料属性数值设计（？级精华）

### ISSUE THREAD

**Issue by ryuujo1573** [TCreopargh/GreedyCraft#156]
## 简单bug简单说

![image](https://user-images.githubusercontent.com/16525512/112715662-949b6400-8f1c-11eb-8697-18f5b7c71b9e.png)
前面的下级精华、初级精华、中级精华、高级精华的手柄数据系数，一般认知上应该是递增的，但是这个终极精华比高级精华整整低了一半（

大佬的原意应该是 手柄系数为4.0+吧？

**Comment by TCreopargh** [comment]
1.34.0已调整
