### ISSUE TITLE
[BUG] black screen or white screen then crash

### ISSUE THREAD

**Issue by xenon-difluoride** [TCreopargh/GreedyCraft#157]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
~~Screen turns white then after a minute or two the game crashes to title screen~~ (edit: it becomes a fucked up version of the screen you see when loading a world, then blackscreens) , this happens upon joining my save after updating. I had 4 chaotic stabilized mob spawners (making zombies) running, so it might be an issue tied to too many mobs and/or specific mob nbt data.

**To Reproduce**

**Expected behavior**
no crash

**Screenshots**

**Crash reports or logs**
https://paste.ubuntu.com/p/5YydGVSF66/

**Details**
Please fill out the blanks below:
Modpack Version: (1.34.0)
Did you add or remove mods? (no)
Did you edit any config or script? (yes, configs only, none particularly likely to cause issues)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (default)
Singleplayer, LAN game or server pack? (singleplayer)

**Additional context**

**Comment by xenon-difluoride** [comment]
update: I tried making a compact sky world in creative, I joined, it worked, and the graphics were fucked up, then I turned off vbos and I get a different crash every time I join that or a new world (without restarting), I turned on VBOs and everything flickers in a new world but I can join it

**Comment by xenon-difluoride** [comment]
ignore my previous comment, my world still has the issue except now it blackscreens instead, the other was because I messed up shader settings somehow

**Comment by TCreopargh** [comment]
Find Entity culling in mod settings and try to adjust settings in it, if it's fixed please tell me which option you turned on/off, if none of the buttons work you can just turn off the master switch that disables the entire mod and it should be fixed

**Comment by xenon-difluoride** [comment]
fuck, vanillafix is broken after the shader fix, and I need to restart on a crash

`[22:32:30] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[22:32:30] [Client thread/ERROR] [minecraft/Minecraft]: @ VanillaFix GUI Loop
[22:32:30] [Client thread/ERROR] [minecraft/Minecraft]: 1280: Invalid enum`
seems to be tied to vanillafix

**Comment by YoItSoul** [comment]
This is consistent with what I'm experiencing as well, but it has nothing to do with the steps listed above, simply joining a world causes a un-recoverable black screen. The only way to get out of it is force closing the application.

**Comment by TCreopargh** [comment]
Try to just remove EntityCulling, it might be causing the problem. If this works please tell me so I can report this to EntityCulling

**Comment by xenon-difluoride** [comment]
I disabled entityculling in its config menu, seems to work currently

**Comment by TCreopargh** [comment]
For anyone having this issue, please do what the author of EntityCulling tells you to do in https://github.com/Meldexun/EntityCulling/issues/18
And tell the author if the bug is fixed or still exists in that issue (as well as providing your latest log file). Thanks!
(Also don't forget to re-enable Entity Culling before you do this)

**Comment by TCreopargh** [comment]
This should have been fixed
