### ISSUE TITLE
[BUG] 舒服细致材质包加载后崩溃

### ISSUE THREAD

**Issue by Skyerk** [TCreopargh/GreedyCraft#168]
# 贪婪整合包 Bug反馈表

## 请在下面详细描述你遇到的Bug

我自己加了一个舒服细致材质包，但是加载之后一进游戏就马上崩溃。

## 如果Bug造成了崩溃，请将崩溃报告的链接粘贴在下面

https://paste.ubuntu.com/p/hmGkVxRgWd/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 进游戏后加载材质包“舒服细致”
2. 进入世界
3. 崩溃。

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.34.0.114.0
 * Java版本：1.8.0.281
 * 分配的内存：16384
 * 物理内存：32G
 * 是否增减了mod：没有
 * 是否修改了材质包：增加了“舒服细致材质包”
 * 是否修改了魔改/配置文件：没有
 * 使用的光影（如果不是渲染问题可以不填）：已选择“内置”
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：I7-9700K+RTX2080
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.33.0.xxx
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

已确认是小地图与材质包冲突。能否在下个版本中更换一个小地图mod？最初的小地图mod与材质包似乎并不冲突，当时游玩了很久。

**Comment by TCreopargh** [comment]
不处理和第三方mod、材质包、光影的兼容问题
