### ISSUE TITLE
Could not understand pack manifest: Document is not an object[BUG] 

### ISSUE THREAD

**Issue by CorsonForge** [TCreopargh/GreedyCraft#170]
**Describe the bug**
When trying to add instance to MultiMC I receive the error **Could not understand pack manifest: Document is not an object**

**To Reproduce**
1. Drag zip file into MultiMC

**Expected behavior**
GreedyCraft Instance to be added

**Screenshots**
![Capture](https://user-images.githubusercontent.com/64653583/113462578-729b5900-93d6-11eb-847d-871ecc945843.PNG)
.

**Details**
Please fill out the blanks below:
Modpack Version: ( **1.34.1.115** )
Did you add or remove mods? ( **NO** )
Did you edit any config or script? ( **NO** )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( **NO** )
Singleplayer, LAN game or server pack? ( **SINGLEPLAYER** )

**Additional context**
I have updated my java and tried downloading the zip file from both the curse forge site as well as here on github and receive the same error with both versions.

**Comment by TCreopargh** [comment]
Try to unzip the zip file and repack it?

**Comment by CorsonForge** [comment]
I was able to get it to work after I restarted my computer. Looks like some things just needed to update.
