### ISSUE TITLE
[BUG] 实用扩展面团合成数量不对

### ISSUE THREAD

**Issue by FallDark** [TCreopargh/GreedyCraft#171]
## 请在下面详细描述你遇到的Bug
![20210404191627](https://user-images.githubusercontent.com/25171639/113506970-5e905c80-957a-11eb-8966-f5fdf0b0a681.png)
8个合成出1个
## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.34.1.115.1
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否

**Comment by TCreopargh** [comment]
游戏设定
