### ISSUE TITLE
[BUG]can't play, game crashes after about 5 minutes

### ISSUE THREAD

**Issue by MzzVixen** [TCreopargh/GreedyCraft#173]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [ X ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

**Details**
Please fill out the blanks below:
Modpack Version: ( both 1.33 & 1.34  )
Did you add or remove mods? ( no )
Did you edit any config or script? (  no )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( no )
Singleplayer, LAN game or server pack? ( single  )

**Additional context**
MultiMC version: 0.6.12-1530

 2x uninstall and reinstall, 4 different launchers, and 16 gigs mem allocated each time for the game,

**Comment by TCreopargh** [comment]
I can't even tell the problem because you don't provide anything. Crashing to desktop is memory problem and please read the installation guide to resolve it

**Comment by MzzVixen** [comment]
sorry new to this, I don't know how to post just a link to my report
