### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MzzVixen** [TCreopargh/GreedyCraft#174]
[12:10:09] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in biggerpacketsplz-since1.8-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

**Details**
Please fill out the blanks below:
Modpack Version: (1.33 and 1.34  )
Did you add or remove mods? ( no new install also  )
Did you edit any config or script? ( didn't touch anything but do the memory allocation )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( Default )
Singleplayer, LAN game or server pack? ( single)

![error](https://user-images.githubusercontent.com/44417490/114282963-10f17500-99fc-11eb-9389-5628ec54cf21.jpg)
![ram](https://user-images.githubusercontent.com/44417490/114282964-15b62900-99fc-11eb-99ef-29cfd81163a2.jpg)

https://paste.ubuntu.com/p/YrZK5n3G4G/
https://paste.ee/p/rSlyF

I've tried both the older version of the game and the new version, both I allocate 16 gigs of my 32 gigs, and on about 4 different launchers. All have the same problem, after about 5 minutes of playing, the game freezes my system then crashes to desktop,  

if I'm posting incorrectly please excuse me, this is my first time (besides the tombstone lol) that I have posted and am still learning.

thank you for any help

**Comment by TCreopargh** [comment]
That's just a warning and not the thing that crashed the game, I'm sure your game just runs out of memory and crashes with a weird exit code, try allocating only 10GB
