### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oskskills** [TCreopargh/GreedyCraft#175]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [ X] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
I am trying to craft the Twilight Gem to go to the Twilight Forest, but although the gem shows up in the output slot on the crafting station it refuses to actually be took out and stays, shift-clicking puts a "Copy" in my inventory which stays until open it up where it will disappear and return to the crafting station.

**To Reproduce**
1. Put all the required items in the crafting station (manually or via JEI)
2. take the item out of the crafting station.

**Expected behavior**
I should be able to put it in my inventory and continue with progression on the modpack

**Screenshots**

https://user-images.githubusercontent.com/1090654/114288444-ed641400-9a67-11eb-86e9-1f47eed1b0e3.mp4

**Crash reports or logs**
N/A

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.1115.1 )
Did you add or remove mods? (No )
Did you edit any config or script? (No )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default)
Singleplayer, LAN game or server pack? (Server Pack)

**Additional context**

**Comment by TCreopargh** [comment]
If you play on a server make sure your client packmode is the same as the server side packmode, in this case you should switch your client to expert mode
