### ISSUE TITLE
tried doing what you said still crashes

### ISSUE THREAD

**Issue by MzzVixen** [TCreopargh/GreedyCraft#176]
"That's just a warning and not the thing that crashed the game, I'm sure your game just runs out of memory and crashes with a weird exit code, try allocating only 10GB"

https://paste.ubuntu.com/p/Swsdpxzkmm/
and 
https://paste.ee/p/a0oci
and
https://paste.ee/p/a8fnJ

the ones from the other day

https://paste.ubuntu.com/p/YrZK5n3G4G/
https://paste.ee/p/rSlyF

I had been playing for several weeks with no problem, then crashed after updating,  uninstalled the newer version after a few tries on other launchers,  and the same thing happens now with the older version of the pack. 

It must be something with my computer  but haven't a clue, it's a brand new build, and as I said before it played the game for a couple weeks with no problem.

**Comment by MzzVixen** [comment]
[17:47:27] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2142ms behind, skipping 42 tick(s)

**Comment by TCreopargh** [comment]
Can you find a hs_err_pid file under your modpack directory that's generated right after the crash?

**Comment by MzzVixen** [comment]
checking now, and starting game if I don't find it lol_

**Comment by MzzVixen** [comment]
no hs_err_pid  on my computer at all, checked before and after game crash

**Comment by TCreopargh** [comment]
Hmm it's not memory problem then, but I'm sure 'cant keep up' can't crash your game at all, try using a different save file and see if it still crashes?

**Comment by MzzVixen** [comment]
I'm doing a new game each time, random seed and title, still trying to get grass lol

**Comment by TCreopargh** [comment]
So your game just instantly crash to desktop, no crash screen is displayed?

**Comment by MzzVixen** [comment]
yea, I'll be trying to get plant fiber, it will lock up (the whole computer, not just the game) then crash to desktop, the launcher will open back up and have the crash window

**Comment by TCreopargh** [comment]
that sounds like a memory problem in any way, especially it doesn't output anything useful in logs
Try restarting your computer and allocating 10GB and remove all irrelevant background procrsses and try again, see if this time it lasts longer

**Comment by MzzVixen** [comment]
ok doing it now

**Comment by MzzVixen** [comment]
ok tried it twice, lol, still crashes before I can even get enough mats to make the crude hatchet lol.  new game, new seed, fresh update of vid driver and java, should I try deleting game pack and reinstalling it? and do you need the error logs for the new crashes/

**Comment by MzzVixen** [comment]
oh and still now hs_err_pid anywhere on my computer, we did a whole system search and it didn't find any

**Comment by TCreopargh** [comment]
Try to reinstall it and use openJ9 Java environment. Also try allocating some virtual memory

**Comment by MzzVixen** [comment]
uninstalled, will continue doing what you suggested in the morning, thank you for your help

**Comment by MzzVixen** [comment]
sorry it's been a couple days, tummy bug's got me, I've uninstall and am reinstalling everything, son won't like me do the virtual machine lol, he's boss will try this and let you know, I'm also checking to see if it could be a problem with my vid card and it.  thank you for your help again

**Comment by MzzVixen** [comment]
https://paste.ee/p/5xYL4

**Comment by MzzVixen** [comment]
I uninstalled the pack, all the launchers, and java, made sure I had the correct java version and the newest modpack and tried again

**Comment by TCreopargh** [comment]
Looks like an error with Sound Physics, try to uninstall the mod and see if it helps?

**Comment by MzzVixen** [comment]
so we (and by we I mean one of my awesome sons) figured out what was wrong, not only could I not play this modpack, but I also couldn't play almost any game,.... my brand new less than a month old vid card died..... color me very unhappy

**Comment by MzzVixen** [comment]
thank you for all your help! I really really appreciate it, I am able to play the game now, my said awesome son is letting me borrow his vid card. and I'm happily playing right now

**Comment by TCreopargh** [comment]
Time to get a new vid card I guess
