### ISSUE TITLE
[Suggestion] 加长内存清理mod清理间隔时间

### ISSUE THREAD

**Issue by Yisenayan** [TCreopargh/GreedyCraft#18]
## 描述你的想法或建议
5分钟的时间过于短，容易5分未响应一次
（这好吗？这不好）

## 你是否有实现该想法的方法或建议？如果有，请说明
加长清理内存间隔时间

**Comment by Yisenayan** [comment]
另外1.16.1，R键的内存清理显示找不到指令

**Comment by TCreopargh** [comment]
找不到指令可能是你没安装正确，你试下/cleanmemory看看可以不

**Comment by TCreopargh** [comment]
0f9f73058c4f4b6939f8d97a5f6dd95b8c6d6da0
