### ISSUE TITLE
iswuss GameStage

### ISSUE THREAD

**Issue by HushabyeValley** [TCreopargh/GreedyCraft#183]
After re-creating spawn after an _incident_ occurred, all Admins and OPs involved have been given the GameStage of iswuss, making it impossible for them to play normally now. They can no longer have the fun of guessing what an item is, needing a pouch to pick it up or even joining Incognito (Due to it classing them as a cheat and sending an announcement to the entire chat).

Is it possible to remove this "cheat" system for servers, allowing staff who **need** access to these commands to play normally with the rest of the server?

**Comment by TCreopargh** [comment]
Use command line to execute commands, also iirc I disabled command whitelist for the server pack.
