### ISSUE TITLE
[BUG] Nether Wart Right Click Crash

### ISSUE THREAD

**Issue by BDWSSBB** [TCreopargh/GreedyCraft#190]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Right clicking fully grown nether warts crashes the game.

**To Reproduce**
Right click fully grown nether warts. You should crash.

**Expected behavior**
You should harvest/replant the nether wart and not crash.

**Crash reports or logs**
https://paste.ubuntu.com/p/33bT9g3zsd/

**Details**
Modpack Version: 1.35.1
Did you add or remove mods: Removed Better Foliage
Did you edit any config or script: No
Using shaders: Default
Singleplayer, LAN game or server pack: Singleplayer

**Comment by TCreopargh** [comment]
Fixed in 1.35.2
