### ISSUE TITLE
[BUG] New update, White loading screen, not old custom one. Crashes Every time, says custom loading screen mod causes crash.  

### ISSUE THREAD

**Issue by EAGBCD** [TCreopargh/GreedyCraft#193]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [X] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Title 

**To Reproduce**
Install new update
Start the game
Wait ~10 Min
Crash

**Expected behavior**
Normal loading and game works

**Screenshots**

**Crash reports or logs**

https://paste.ubuntu.com/p/j8cvMFCBqH/

**Details**
Please fill out the blanks below:
Modpack Version: (Newest update, the old one worked fine)
Did you add or remove mods? (No Just download and click play, with correct RAM settings )
Did you edit any config or script? (No completely as downloaded from CF)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Doesn't matter not in the game)
Singleplayer, LAN game or server pack? ( Same as above)

**Additional context**

Did you update the custom loading screen mod? I would try to roll that back and see if it fixes this.

Thanks for the help.

**Comment by EAGBCD** [comment]
I removed the custom loading screen mod and added the version from the previous GreedyCraft version and it loaded and seemed fine. Need to test later to make sure gameplay is all good but might have solved this I hope.

**Comment by TCreopargh** [comment]
Also try to update it to the latest version of CustomLoadingScreen which may have fixed that, the latest version will be included in next update

**Comment by TCreopargh** [comment]
Should be fixed in 1.35.2
