### ISSUE TITLE
[BUG] ME Interface quest rewards Disabled Item

### ISSUE THREAD

**Issue by anabsolutesloth** [TCreopargh/GreedyCraft#195]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
"Advanced Transport" quest in Applied Energistics tab grants a disabled item.

**To Reproduce**
1. Open Questbook
2. Go to Applied Energistics tab
3. Click on Advanced Transport quest
4. See that it grants a disabled item (Cyclic Extraction Cables)

**Expected behavior**
For the quest to grant an item that is not disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/63694982/121459834-cf7c3800-c960-11eb-98d9-9f609fcc36fe.png)

**Crash reports or logs**

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.35.117.1 )
Did you add or remove mods? ( No )
Did you edit any config or script? ( No )
Using shaders? ( None )
Singleplayer, LAN game or server pack? ( Server )

**Additional context**

**Comment by TCreopargh** [comment]
Fixed in 1.35.2
