### ISSUE TITLE
[BUG] Duplication glitch with Evolved trait

### ISSUE THREAD

**Issue by EnigmaticaGH** [TCreopargh/GreedyCraft#199]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
When attempting to replace a tool part that has an Evolved trait on it, the tool part you are attempting to replace with gets duplicated. This appears to be a desync issue, but the items are actually duplicated.

**To Reproduce**
1. Get a tool, weapon, or armor (in my case I tested with armor) with a part containing the Evolved trait
2. Using a Tool/Amor Forge, try to replace the Evolved part with something else. The Forge will tell you the part cannot be replaced
3. When taking your part out of the tool forge, it is sometimes duplicated. This works on the entire itemStack, so if you put in, say, 16 helmet cores, it will duplicate to 32.

**Expected behavior**
The item(s) will not be duplicated

**Screenshots**
https://streamable.com/z0i00h

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.35.1 )
Did you add or remove mods? ( LagGoggles added )
Did you edit any config or script? ( Disabled player animations from MoBends )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( Default )
Singleplayer, LAN game or server pack? ( Server Pack )

**Additional context**
N/A

**Comment by EnigmaticaGH** [comment]
Apparently this is the same issue as #134 and it's been closed on both repos so maybe this is fixed in 1.35.2 or at least known

**Comment by TCreopargh** [comment]
The bug is fixed on the TconEvo side but the version is not in the pack yet due to incompatibility issues.

**Comment by TCreopargh** [comment]
Looks like the latest version of TConEvo might have fixed the incompatibility issue. Will try to update later
