### ISSUE TITLE
进入暮色无法完成任务目标

### ISSUE THREAD

**Issue by wbf5459** [TCreopargh/GreedyCraft#2]
在专家模式游玩至进入暮色森林维度后，无法完成任务目标：访问维度：twilight_forest,开了两个档都有这种情况，第一次是1.12.3的版本，此次是1.13.1的版本

**Comment by TCreopargh** [comment]
我看下这个问题

**Comment by wbf5459** [comment]
我加了些其他的mod来降低难度。可能是mod问题，以下是mod列表：
villagesp_1.12-1.0
BetterBuildersWands-1.12-0.11.1.245+69d0d70
torcherino-7.5
Croparia-2.5
CropariaCompatible-1.0.0
EverlastingAbilities-1.12.2-1.5.3
UltimateStack-1.12.2-1.3.1
PPCore-1.12.2-1.3.0

**Comment by wbf5459** [comment]
试验过后发现是如下两个mod的问题，希望可以修复一下。
UltimateStack-1.12.2-1.3.1
PPCore-1.12.2-1.3.0

**Comment by TCreopargh** [comment]
不会处理私自加mod导致的问题。
