### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Speratum** [TCreopargh/GreedyCraft#203]
整合包里有一些物品和文字没有汉化，比如说某模组的知识精华锭，创建世界选择世界类型的世界类型，贪婪整合包的引导书和游戏模式，左上角游戏信息显示和左下角的信息显示等没有汉化。（整合包版本1.35.2）

**Comment by TCreopargh** [comment]
你是从哪里下的整合包？你应该下成国际版本了
