### ISSUE TITLE
[BUG] 世界盐无法右击炼药锅生成坩埚

### ISSUE THREAD

**Issue by MoeRyuu** [TCreopargh/GreedyCraft#206]
# 贪婪整合包 Bug反馈表

## 请在下面详细描述你遇到的Bug

世界盐无法右击炼药锅来生成坩埚，1.34、1.35测试过都无法操作。

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.35.2.118.0
 * Java版本：1.8.0.291
 * 分配的内存：10240M
 * 物理内存：16322M
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：

**Comment by TCreopargh** [comment]
请先完成神秘的前置任务

**Comment by MoeRyuu** [comment]
> 请先完成神秘的前置任务
感谢回复，能合成世界盐之后还有其他的前置吗？我尝试在创造模式下也不能右击

**Comment by TCreopargh** [comment]
看你的神秘书

**Comment by MoeRyuu** [comment]
> 看你的神秘书

感谢，魔导书里点了就能合成了
