### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LimeranceY** [TCreopargh/GreedyCraft#21]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
游戏加载界面，加载完成叮的一声后游戏直接没了，然后出报告。重装游戏，文件全删重装压缩包，重装java，改内存都没用，之前1.6版本能玩，改1.7之后1.6也不能玩了。安装教程的解决方法都试过了，我也不知道算不算BUG想了很久才来反馈，麻烦大大了！

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
https://paste.ubuntu.com/p/YdYvrBDQFk/
## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 启动游戏
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.17
 * Java版本：8u271
 * 分配的内存：10G
 * 物理内存：16G
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：RTX 2080ti   i7-9700K
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
请试下删除整合包根目录下options.txt，如果没有解决请降低分配的内存到8G

**Comment by LimeranceY** [comment]
好的，谢谢大大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TCreopargh/GreedyCraft"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 晚上9:07
收件人:&nbsp;"TCreopargh/GreedyCraft"<GreedyCraft@noreply.github.com&gt;;
抄送:&nbsp;"Big_Chiken"<1350587169@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TCreopargh/GreedyCraft] [BUG]  (#21)





 
请试下删除整合包根目录下options.txt，如果没有解决请降低分配的内存到8G
