### ISSUE TITLE
[BUG] 修改时间可达到加速火把效果

### ISSUE THREAD

**Issue by xhxiaohui** [TCreopargh/GreedyCraft#210]
修改系统时间几次可达到加速火把十分之一的效果 貌似可以叠加 后果会导致掉帧

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1.  修改系统时间

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.35.2
 * Java版本：1.8.0_291
 * 分配的内存：10240
 * 物理内存：16G
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.35.2

**Comment by TCreopargh** [comment]
不是bug是特性
