### ISSUE TITLE
[BUG] 在地狱跑图时崩溃

### ISSUE THREAD

**Issue by LesterThom** [TCreopargh/GreedyCraft#215]
# 贪婪整合包 Bug反馈表

## 请在下面详细描述你遇到的Bug

在地狱跑图时崩溃

## 如果Bug造成了崩溃，请将崩溃报告的链接粘贴在下面

https://paste.ubuntu.com/p/Qszg4rw9sn/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.35.2.118.0
 * Java版本：jre1.8.0_291
 * 分配的内存：10GB
 * 物理内存：16GB
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：整合包自带
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：i5-9400f gtx1650s
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.35.2.118.0

**Comment by TCreopargh** [comment]
存档损坏，请恢复备份
