### ISSUE TITLE
一传送到地狱门就崩溃

### ISSUE THREAD

**Issue by Matryoshkaaa** [TCreopargh/GreedyCraft#219]
# 贪婪整合包 Bug反馈表

## 请在下面详细描述你遇到的Bug

暮光之庇护已经造好并使用了 然后一到地狱还没见到方块就显示内置服务器正在关闭

## 如果Bug造成了崩溃，请将崩溃报告的链接粘贴在下面

https://paste.ubuntu.com/p/DVjxsdc2dF/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 没有 如果作者需要的话我可以提供存档 这个BUG的重现方法仅仅只需要传送过去
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.34.1.115.0
 * Java版本：8 64位
 * 分配的内存：9216
 * 物理内存：16G
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：整合包里面的那个写实光影
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：I5 10400F RTX2060S
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：更新过一次 但我是在更新之后才去的地狱

**Comment by TCreopargh** [comment]
可能是大量岩浆和血连接导致方块更新过多堆栈溢出了，建议你换个地方开门然后走过去

**Comment by Matryoshkaaa** [comment]
@TCreopargh TC大佬 这个问题还是会出现 我换了三个地方 并且都隔着有不小的一段距离 结果都是一样 一到地狱就崩溃 真的非常喜欢这个整合包  但这个问题我实在不知道该怎么解决

**Comment by Matryoshkaaa** [comment]
一到地狱了之后过一会会显示正在关闭内置服务器

**Comment by Matryoshkaaa** [comment]
这是最近一次的日志 https://paste.ubuntu.com/p/48PytkzXKj/

**Comment by Matryoshkaaa** [comment]
存档
链接: https://pan.baidu.com/s/1x25skuwb-hThowEgY66LwA 提取码: 2vp4

**Comment by TCreopargh** [comment]
试下删除存档文件夹里的DIM-1文件夹，这样会使下界重新生成，另外降低视距能够减少加载的区块并避免这种情况，建议进去前把视距调到最小
