### ISSUE TITLE
[BUG] 使用[视域]词条的匠魂装备后画面会不断闪烁

### ISSUE THREAD

**Issue by Xisnow** [TCreopargh/GreedyCraft#22]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
使用[视域]词条的匠魂装备后的夜视效果会让画面会不断闪烁，只会出现在带有视域的盔甲上，带有视域的武器表现正常。

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 戴上有视域词条的匠魂盔甲（如陨星材料的）即可

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.17.1
 * Java版本：1.8.0_271
 * 分配的内存：10240
 * 物理内存：16380
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：默认
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：AMD Ryzen 5 3600 / 七彩虹 iGame GeForce RTX 3070 Ultra OC W
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.12.3 
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法
1.合理怀疑罪魁祸首是3070，舍友的1660ti没有问题

**Comment by Xisnow** [comment]
P.S. 视域武器也会闪烁，只有视域工具显示正常

**Comment by TCreopargh** [comment]
经测试只有在服务端运算跟不上的时候（比如区块加载）的时候会闪烁，我会在下个版本把夜视时间延长到20s。
