### ISSUE TITLE
[BUG] -Server-1.35.2.118.x 运行不了

### ISSUE THREAD

**Issue by daywithday** [TCreopargh/GreedyCraft#220]
# 贪婪整合包 Bug反馈表

## 请在下面详细描述你遇到的Bug

![image](https://user-images.githubusercontent.com/29853752/128655076-40e295e2-bad7-41c0-941d-1dfa72a17fe4.png)

**Comment by daywithday** [comment]
> # 贪婪整合包 Bug反馈表
> ## 请在下面详细描述你遇到的Bug
> ![image](https://user-images.githubusercontent.com/29853752/128655076-40e295e2-bad7-41c0-941d-1dfa72a17fe4.png)

**Comment by ryuujo1573** [comment]
java版本不对吧....
