### ISSUE TITLE
爱看不看

### ISSUE THREAD

**Issue by ghost** [TCreopargh/GreedyCraft#227]
https://www.mcbbs.net/thread-1243313-1-1.html
https://www.curseforge.com/minecraft/texture-packs/open-gui
你似乎很忙，不管用不用给个回复

**Comment by creederyj** [comment]
下载惨淡啊，你那个GUI支持才八九个（请关闭谷歌翻译）

**Comment by creederyj** [comment]
[看看我写的帖子](https://www.mcbbs.net/forum.php?mod=viewthread&tid=1257795&page=1&extra=#pid23326732)，它说明了一切，它需要来一个引子

**Comment by creederyj** [comment]
额...我突然发现那两个gui已经在你的包里了...你看着办吧，用不用都无所谓...我从来没想过两个一起用...
