### ISSUE TITLE
[Suggestion] Add a way to disable the anti-cheat

### ISSUE THREAD

**Issue by Sintinium** [TCreopargh/GreedyCraft#232]
I love this pack but it limiting everything without an easy to way to disable it is kinda annoying and making me not want to play it. I think there should be an easy option to disable the anti-cheat if the player wants to. Thanks!

**Comment by Deadlymousee** [comment]
Totally agree on this one, it ruined the pack for us. All progress is just opened up and no fun in playing with friends that is still locked behind the progress. For the time being we found another pack to play, hopefully this will be changed so we can enjoy this awesome pack later.

**Comment by TCreopargh** [comment]
use /wussmode command

**Comment by anabsolutesloth** [comment]
That just fires the anticheat, does it not?

**Comment by TCreopargh** [comment]
Note that this command can also be destructive to your save file. Using this command will display "cheats" in your scoreboard and permanently lock the ending of the story. It's recommended to use casual mode if you want to play casually.
