### ISSUE TITLE
[BUG] Server crashing upon startup (fresh download)

### ISSUE THREAD

**Issue by TheMilkMan105** [TCreopargh/GreedyCraft#235]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
I just recently found this modpack and wanted to start up a server through ngrok so me and my friends can play it, upon downloading the server pack and following the "README_SERVER_INSALLATION" I ran the "run-windows" bat file and encountered an issue after loading for a bit. I will obviously include the crash report file so that you can look through it yourself. Upon receiving some advice on the discord I redownloaded the server files and started over again just to end up in the same situation. 

**To Reproduce**
1. Go to 'Location of server files'
2. Click on 'run-windows'
3. Scroll down to 'cmd promt'

**Expected behavior**
Not sure if this is a valid answer here but I expected the server to run smoothly as I followed the guide multiple times. 

**Screenshots**
No screenshots just crash report. 

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

Crash report:
[Ubuntu Paste](https://paste.ubuntu.com/p/txHYpPBv6d/) 

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.35.2.118 )
Did you add or remove mods? ( no )
Did you edit any config or script? ( only what was stated in the README )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( default )
Singleplayer, LAN game or server pack? ( serverpack )

**Additional context**
NTA

**Comment by TCreopargh** [comment]
Looks like you messed up the default world generator's config. I forget where the config is, but looks like you added 2 extra brackets into where you need to input the uuid.
Try deleting the entire server folder and unzip a fresh one again, this time when it lets you input the world generator's uuid don't add [] to it
98f16d23-cbcb-11ea-ac7b-005056c00008 not [98f16d23-cbcb-11ea-ac7b-005056c00008]
