### ISSUE TITLE
game crashes to main menu when looking at quests[BUG]

### ISSUE THREAD

**Issue by damiano2233** [TCreopargh/GreedyCraft#236]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x ] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
when i open the quests it leaves the would and says oops greedycraft crashed says that it could be this's mods hungertweaker, applecore, appleskin, FTBLibrary

**To Reproduce**
1. Go to 'inventory '
2. Click on 'quests'
3. See error

**Expected behavior**
game sends you to main menu and says it crashed

**Crash reports or logs**
[If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.](https://pastebin.com/9PLHTjeZ)

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.35.2.118.1 )
Did you add or remove mods? ( removed twilight forest  )
Did you edit any config or script? ( changed bountiful.cfg to remove the twilight forest stuff )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( no shaders )
Singleplayer, LAN game or server pack? ( server and singleplayer )

**Comment by anabsolutesloth** [comment]
Find and post the Crash Log, very difficult to help without it.

**Comment by damiano2233** [comment]
its in the pastebin link
