### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by zjh790** [TCreopargh/GreedyCraft#24]
## 描述你的想法或建议
加个自动领任务奖励并输出的方块吧，到了后期挂机的东西太多，但是任务又领不了，非常麻烦

**Comment by TCreopargh** [comment]
已经有这种方块了，搜@ftbquests

**Comment by zjh790** [comment]
我做了任务显示器，进度显示器，进度检测器，没有一个可以

**Comment by TCreopargh** [comment]
有一个长的像箱子，忘了叫啥了，你找找
