### ISSUE TITLE
java.lang.IllegalArgumentException: Name and ID cannot both be blank

### ISSUE THREAD

**Issue by EnvyPig** [TCreopargh/GreedyCraft#243]
[crash-2022-02-03_12.00.17-client.txt](https://github.com/TCreopargh/GreedyCraft/files/7991752/crash-2022-02-03_12.00.17-client.txt)
# 贪婪整合包 Bug反馈表

## 请在下面详细描述你遇到的Bug

java.lang.IllegalArgumentException: Name and ID cannot both be blank

## 如果Bug造成了崩溃，请将崩溃报告的链接粘贴在下面

java.lang.IllegalArgumentException: Name and ID cannot both be blank

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 无论是新建世界还是回档都无法解决
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：最新
 * Java版本：8
 * 分配的内存：10g
 * 物理内存：16g
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：

**Comment by EnvyPig** [comment]
[crash-2022-02-03_12.00.17-client.txt](https://github.com/TCreopargh/GreedyCraft/files/7991761/crash-2022-02-03_12.00.17-client.txt)

**Comment by EnvyPig** [comment]
配置文件改了online-mode=false

**Comment by TCreopargh** [comment]
请使用正版登录，或者至少起个正常的名字
