### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ksiedzu** [TCreopargh/GreedyCraft#249]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [ x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**

**To Reproduce**

**Expected behavior**
im just want repair mc from crashing and keep playing
**Screenshots**

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.
https://pastebin.com/yx21sAha

**Details**
Please fill out the blanks below:
Modpack Version: ( LWJGL 2 v 2.9.4-nightly-20150209
mc 1.12.2
forge 14.23.5.2855 )
Did you add or remove mods? ( i added essential and overloaded armor bar and disabled passable leaves )
Did you edit any config or script? (no  )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (  default)
Singleplayer, LAN game or server pack? (singleplayer  )

**Additional context**
yesterday everything was alright today i opened mc and it just happened

**Comment by Ksiedzu** [comment]
i forgot describe sry mc is just crashing on start

**Comment by MCSuperplayer** [comment]
Look at what version of Redstone arsenal you have installed and download a fresh copy of that from curseforge
Then put the new file into your mods folder

**Comment by MCSuperplayer** [comment]
Remember to take the old one out of there first

**Comment by Ksiedzu** [comment]
i downgraded from 2.6.6.1 to 2.6.3.18 and it didnt help

**Comment by Ksiedzu** [comment]
i tried also deleting optifine and using other version of Redstone Arsenal but it didnt help too i ask about help on mod dev server but they said thats mixin issue and their mod work fine

**Comment by Ksiedzu** [comment]
i solved case by my self everything is fine now
