### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by qingyu114514** [TCreopargh/GreedyCraft#25]
bug描述

您好，生草的Tc同志，1.17.1默认的高清修复版本过高导致ender io并不支持，游戏会在加载途中崩溃

解决方法：
1.将高清修复调至HD_U_F5而不是默认的F6

 * 整合包版本：1.17.1
 * Java版本：
 * 分配的内存：默认10G
 * 物理内存：16G DDR4 2666mhz
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：没开
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：3500X/RX580
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.17.1

**Comment by qingyu114514** [comment]
java版本:8u271,64位= =

**Comment by TCreopargh** [comment]
并没有这个问题，enderio无法加载一般是内存问题，另外光影只支持F6
