### ISSUE TITLE
[BUG] modpack zip unable to import

### ISSUE THREAD

**Issue by lokzz** [TCreopargh/GreedyCraft#258]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
unable to import modpack zip to multiMC
**To Reproduce**
1. drag zip to multimc, click ok.
2. wait
3. "archive does not contain a recognized modpack type"
**Expected behavior**

**Screenshots**

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

**Details**
Please fill out the blanks below:
Modpack Version: (GreedyCraft-1.35.2.118.1)
Did you add or remove mods? (no)
Did you edit any config or script? (no)
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (N/A)
Singleplayer, LAN game or server pack? (Singleplayer)

**Additional context**

**Comment by sykefu** [comment]
Have the same problem.

**Comment by anabsolutesloth** [comment]
MultiMC no longer supports installing modpacks via Curseforge.
However, a Fork of it, [PrismLauncher](https://github.com/PrismLauncher/PrismLauncher), does, so you should be able to apply Prism to all mentions of MultiMC in the installation guide.
