### ISSUE TITLE
长时间使用勾爪概率关闭内置服务器

### ISSUE THREAD

**Issue by Yisenayan** [TCreopargh/GreedyCraft#3]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述：长时间使用勾爪时概率被强制关闭内置服务器，理由是服务器禁止飞行，并且重新进入时也有可能保持那个状态而继续被踢出（也有可能是我进存档比较慢）,一直无法进入的话就只能回档

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.14.1
 * Java版本：java8（1.8.0.271）
 * 分配的内存：13G
 * 物理内存：16G
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：§9(默认, §eBSL修改版§9)§e ComplementaryShaders_3.08_dev5
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：i5-9300h,GTX 1650
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.11.1
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
查看下存档内的server.properties里面的allow_flight选项是否为true？若为false请改成true然后重启游戏

**Comment by Yisenayan** [comment]
已修改，效果在检验
