### ISSUE TITLE
[BUG] 新发现的刷怪笼不刷怪

### ISSUE THREAD

**Issue by Lounode** [TCreopargh/GreedyCraft#32]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
当你在野外找到一个刷怪笼时（尤其是遗迹以及暮色等地区的刷怪笼）会发出大量烟雾粒子效果，表现为无法产生新的怪物，然而它们却都是刚刚生成连一只怪物也未刷的。
初步断定是刷怪笼控制的问题，但是原理未知，不清楚解决方法。

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 进入暮色或在主世界找到一些非战斗高塔的遗迹
2. 观察里面的刷怪笼
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：
 * Java版本：1.8.0_271
 * 分配的内存：10Gib
 * 物理内存：16Gib
 * 是否增减了mod：是（客户端mod）
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：无
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.16
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
此为游戏设定，任何刷怪笼刷完一定数量怪物后就不会再刷任何怪物。

**Comment by Lounode** [comment]
@TCreopargh 只是这是新发现的啊，尤其是暮色里刚生成的刷怪笼 他们连一只怪也没刷过啊？

**Comment by TCreopargh** [comment]
已经刷过了，只是你没看见而已

**Comment by TCreopargh** [comment]
重新打开该issue，该问题某些状况下确实存在

**Comment by TCreopargh** [comment]
b74aa46bb27c6c85f2e77d6a37c5d2e39d38b179
