### ISSUE TITLE
关于模组的建议

### ISSUE THREAD

**Issue by Aleftal-null** [TCreopargh/GreedyCraft#33]
希望可以加入巫术学(EBWizardry)

已经检查了兼容性,大概没有严重的Bug,也不会造成卡顿。

我还做了一些巫术学的自定义物品还有FTB任务:

[EBWizardry.zip](https://github.com/TCreopargh/GreedyCraft/files/5738795/EBWizardry.zip)

希望可以采 纳

**Comment by TCreopargh** [comment]
目前不打算新增添加大量内容的mod
