### ISSUE TITLE
匠魂平衡性问题

### ISSUE THREAD

**Issue by ssaxxcvv** [TCreopargh/GreedyCraft#35]
首先 笔者使用版本为1.19.1
未经任何改动
好奇心发了 查阅了自定义匠魂特性的魔改文件
感觉部分特性有些许过头
首先是赌博 10倍伤害后期如果使用在混沌等武器上可以上千伤害 更不用说搭配其他的特性
其次是天地同寿 可以通过一些方法做到1000血量 可以造成很多伤害 并且造价不是很贵
然后知识之力叠加满后的双倍伤害搭配赌博可以做到2000左右的伤害
还有一个问题
在一些极端情况下武器可以做到10w伤 甚至更高
就很离谱
笔者认为有所超模这几个匠魂特性

**Comment by TCreopargh** [comment]
在削了在削了（

**Comment by TCreopargh** [comment]
b74aa46bb27c6c85f2e77d6a37c5d2e39d38b179
