### ISSUE TITLE
生命值异常叠加

### ISSUE THREAD

**Issue by ssaxxcvv** [TCreopargh/GreedyCraft#36]
bug描述
在生命值通过正常手段叠加满后可以通过哥布林杀手套装和巨龙药水异常叠加生命值 最大可以到达1188血量
搭配匠魂武器特性"天地同寿"可以造成不俗的伤害

崩溃报告/日志地址
null

重现bug步骤
1. 穿戴哥布林杀手套装
2. 使用巨龙药水
3. 不出意外生命值就会异常叠加 如没有出现异常叠加重复以上步骤

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.19.1
 * Java版本：jre1.8.0_271
 * 分配的内存：12G
 * 物理内存：32G
 * 是否增减了mod：未增减
 * 是否修改了材质包：未修改
 * 是否修改了魔改/配置文件：未修改

**Comment by TCreopargh** [comment]
哥布林套装是啥鬼啊
非匠魂的装备不是都ban了么

**Comment by ssaxxcvv** [comment]
EXBOT的 ban了么 记不太清了 这个bug很早以前就有了 我测试的时候是开的创造档

**Comment by TCreopargh** [comment]
已（彻底）禁用哥布林套装
