### ISSUE TITLE
杀完凋零后进不去天境

### ISSUE THREAD

**Issue by ketbobo** [TCreopargh/GreedyCraft#38]
建好天境传送门之后，站在门里传送不了，只有粒子效果没有进入天境
![Jre1 8 0_271 Screenshot 2020 12 31 - 13 50 04 10](https://user-images.githubusercontent.com/76803784/103396611-33f3c980-4b6f-11eb-915f-e222c3a0eef7.png)

**Comment by TCreopargh** [comment]
请说明游戏版本，这个1.20.1应该已经修了

**Comment by TCreopargh** [comment]
请更新，1.20.1已经修复
