### ISSUE TITLE
[BUG] 远古生物/原始生物（Primitive Mobs），及其依赖库Multi Mob Library导致的游戏假死问题

### ISSUE THREAD

**Issue by Lounode** [TCreopargh/GreedyCraft#39]
**贪婪整合包 Bug反馈表**

### 远古生物/原始生物（Primitive Mobs），及其依赖库Multi Mob Library导致的游戏假死问题

bug描述

在1.17加入的远古生物及其依赖库会导致游戏假死。

（目前已有多人受害）

## 崩溃报告/日志地址

https://paste.ubuntu.com/p/4vysdq7Smc/

另一个受害者（QQ：3116569404）：https://paste.ubuntu.com/p/4QhgrRCcrN/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：

\1.  64难度 在夜晚偶尔会出现血量bug的远古生物

\2. 当渲染这种生物后，服务器出现假死等问题，回档或清实体解决

\3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）

 \* 整合包版本：1.20.1

 \* Java版本：群文件内版本

 \* 分配的内存：10G

 \* 物理内存：16G

 \* 是否增减了mod：无

 \* 是否修改了材质包：无

 \* 是否修改了魔改/配置文件：无

 \* 使用的光影（如果不是渲染问题可以不填）：

 \* CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：

 \* 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.16

 

## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

本mod的兼容性问题在原curseforge https://www.curseforge.com/minecraft/mc-mods/multi-mob-core 就已经被讨论过，且当前mod已处于弃坑状态，建议删除。

以上

**Comment by TCreopargh** [comment]
目前这个mod有较多魔改不方便删除，我找下解决方法

**Comment by Lounode** [comment]
已确认在1.21.0重现 https://paste.ubuntu.com/p/fnWcvdgsZ4/

**Comment by Lounode** [comment]
提供复现用存档：链接：https://pan.baidu.com/s/1qYBCpHysv69VkAK1AeybEg 提取码：9f5b 
主世界坐标：-275 84 264 附近
复现方法：夜晚时在大坑四处转转，高概率触发。

**Comment by TCreopargh** [comment]
感谢提供，不过能否在QQ上发下？加我好友备注下你是github上的就行，百度盘我不是会员也目前没有客户端或加速软件不太方便。

**Comment by Lounode** [comment]
本问题已在整合包版本1.21.1修复，Issue关闭

**Comment by Lounode** [comment]
重现于最新版本1.21.3 群里已有多人受害

**Comment by TCreopargh** [comment]
已与1.22.1修复
