### ISSUE TITLE
[BUG] 进地图一分钟不到就直接崩溃，没有卡顿，游戏窗口直接消失，然后出现游戏非正常退出，好几次了

### ISSUE THREAD

**Issue by suan-fa** [TCreopargh/GreedyCraft#46]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.21.2
 * Java版本：java8,211
 * 分配的内存：10240
 * 物理内存：16*1024
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：i710750H,GTX1650TI
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 1.21.2
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。
[crash-2021-01-03_09.53.49-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5761104/crash-2021-01-03_09.53.49-client.txt)

解决方法

**Comment by TCreopargh** [comment]
这是内存问题，请降低你所分配的内存。

**Comment by suan-fa** [comment]
[crash-2021-01-03_10.38.39-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5761123/crash-2021-01-03_10.38.39-client.txt)
不行无法启动了

**Comment by suan-fa** [comment]
把内存调回去也不能启动了

**Comment by suan-fa** [comment]
试了两次

**Comment by TCreopargh** [comment]
请确认optifine版本为HD_FU_6_Pre1

**Comment by suan-fa** [comment]
[crash-2021-01-03_12.08.03-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5761187/crash-2021-01-03_12.08.03-client.txt)
还是不行，我已经下载了群里的1.21.3了，什么都没改，进去，然后进地图，然后没了（关了光影也是）

**Comment by TCreopargh** [comment]
试下卸载optifine？

**Comment by qianyi777** [comment]
整合包版本：1.21.3
Java版本：java8,211
分配的内存：10240
物理内存：16*1024
是否增减了mod：是（删除了四季）
是否修改了材质包：否
是否修改了魔改/配置文件：否
使用的光影（如果不是渲染问题可以不填）：
CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：i59400F,gtx1660
创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.21.3
https://paste.ubuntu.com/p/YYVGctKkyR/

**Comment by TCreopargh** [comment]
请更新你的Java，如果还不行请考虑重新安装下
