### ISSUE TITLE
进入地图后过一会就未响应 也不崩溃 就是一直未响应 后台看游戏的占用率是0% 然后强行关后 出现了崩溃的报告[BUG] 

### ISSUE THREAD

**Issue by midouzi7** [TCreopargh/GreedyCraft#47]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
进入地图后过一会就未响应 也不崩溃 就是一直未响应 后台看游戏的占用率是0% 然后强行关后 出现了崩溃的报告

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
https://paste.ubuntu.com/p/mgSMQGVBvF/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 无
2. 无
3. 无

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.21.3
 * Java版本：8u271
 * 分配的内存：9.5g
 * 物理内存：16g
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：进默认的光影
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：i5-9300h1660ti
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：好像是1.13？就进进地图那个界面 存档下面的那窜数字吧
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法
无

**Comment by TCreopargh** [comment]
请勿重复提交，内存分8G即可解决

**Comment by midouzi7** [comment]
但是作者大大&nbsp;我原来分配8g的时候玩一会那个内存就超标&nbsp;然后就是100%我就会卡主&nbsp;过一会又好&nbsp;但是过几十秒又会100%然后卡主的
我用游戏里面的清内存和清实体&nbsp;也没有用&nbsp;那个就显示清理完成后但是我内存占用还是一下子就100%
所以我想问一下&nbsp;如果我自己在加更内存条上吧运行内存升高到24g就可以分配高一些的内存（可以的话24g分配多少？）
还是说其他原因 ？&nbsp;谢谢作者大大了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TCreopargh/GreedyCraft"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月3日(星期天) 下午3:47
收件人:&nbsp;"TCreopargh/GreedyCraft"<GreedyCraft@noreply.github.com&gt;;
抄送:&nbsp;"ぼくのめぐみ美如画中仙"<2323648600@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TCreopargh/GreedyCraft] 进入地图后过一会就未响应 也不崩溃 就是一直未响应 后台看游戏的占用率是0% 然后强行关后 出现了崩溃的报告[BUG]  (#47)





 
请勿重复提交，内存分8G即可解决

**Comment by TCreopargh** [comment]
你可能后台太多软件了，建议升级内存条

**Comment by TCreopargh** [comment]
（或者可以把系统重装一遍

**Comment by midouzi7** [comment]
我重装了过了 我后台全部都关了 现在8g也要未响应了  只要传送几次基本又未响应 主要我开了游戏我内存占用率也就85%呀

**Comment by TCreopargh** [comment]
可以尝试下9G
