### ISSUE TITLE
[Suggestion] 服务端后台自动刷新指令

### ISSUE THREAD

**Issue by denke123** [TCreopargh/GreedyCraft#48]
我用您的整合包开了个服务器，当然 是几个小伙伴一起玩的公益服

但是后台一直重复执行指令：Server 执行命令: /gamerule keepInventory true

就算在游戏开启创造模式也会重复自动开启

请问可以在哪里关闭这一设置呢？

**Comment by TCreopargh** [comment]
可以在scripts文件搜索并关闭，这个是控制游戏模式切换后是否保留物品栏的
