### ISSUE TITLE
[BUG] 游玩过程中出现waiting for server

### ISSUE THREAD

**Issue by WHiteSlience** [TCreopargh/GreedyCraft#49]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
在游玩一段过程后，无法于世界内任何物品进行交互，所有物品的属性下面（不再显示使用什么什么可采集）显示waiting for server，玩家不会受到伤害或攻击，游戏也不会退出或是崩溃，但下次启动时自动存档会回到游戏之前。

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
无崩溃

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.21.3-fix
 * Java版本：java 10 64位
 * 分配的内存：6G
 * 物理内存：8G
 * 是否增减了mod：否
 * 是否修改了材质包：增加了内置的材质包
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：§a(推荐, §d鲜艳§a) §bSEUS-Renewed-v1.0.1.zip
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：十代I5   RTX 2060 6G
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：未使用更新，以1.21.3-fix创建
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法 重启游戏，但是会丢失进度

**Comment by TCreopargh** [comment]
麻烦提供下出现该问题前后的游戏日志（在logs文件夹找到）

**Comment by WHiteSlience** [comment]
好的，我会在1.18号发送过来。 之后我会尝试在不同配置的情况下去实验（那台电脑不在身边）如果依然发现上述问题，我会重新提交一份报告。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;TCreopargh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月4日(星期一) 中午12:18
收件人:&nbsp;&quot;TCreopargh/GreedyCraft&quot;<GreedyCraft@noreply.github.com&gt;;
抄送:&nbsp;&quot;WHiteSlience&quot;<2905416795@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TCreopargh/GreedyCraft] [BUG] 游玩过程中出现waiting for server (#49)

**Comment by Lounode** [comment]
> 好的，我会在1.18号发送过来。 之后我会尝试在不同配置的情况下去实验（那台电脑不在身边）如果依然发现上述问题，我会重新提交一份报告。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;TCreopargh&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月4日(星期一) 中午12:18 收件人:&nbsp;&quot;TCreopargh/GreedyCraft&quot;<GreedyCraft@noreply.github.com&gt;; 抄送:&nbsp;&quot;WHiteSlience&quot;<2905416795@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [TCreopargh/GreedyCraft] [BUG] 游玩过程中出现waiting for server (#49)

请尝试删除原生怪物，及其前置multiMobLibrary

**Comment by TCreopargh** [comment]
1.22.1已修复

**Comment by WHiteSlience** [comment]
OK






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TCreopargh"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 下午5:55
收件人: "TCreopargh/GreedyCraft"<GreedyCraft@noreply.github.com&gt;; 
抄送: "どうしても考えたくなかっ"<2905416795@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [TCreopargh/GreedyCraft] [BUG] 游玩过程中出现waiting for server (#49)





 
1.22.1已修复
