### ISSUE TITLE
国际化计划

### ISSUE THREAD

**Issue by TCreopargh** [TCreopargh/GreedyCraft#5]
贪婪整合包计划在不久的将来进行国际化，即：将整合包内的中文内容翻译为英文然后上传到Curseforge。
由于同时维护两个版本难度很大，因此该计划预计将在版本稳定并且基本不会再有大版本更新后实施。
目前的打算是国际版为单独的版本，不进行LangKey翻译，因为存在部分config内容无法翻译且一个人进行LangKey翻译的工作量太大。
另外，Curseforge不允许整合包内包含不在Curse上发布的mod，这表明当前整合包的内容会在国际化过程中进行删减，比如另一个通用bug修复等mod将无法在Curseforge上发布。
由于Optifine作者不允许整合包内包含Optifine，目前整合使用启动器的方式自动安装Optifine，但Curseforge上发布的整合包肯定不能带启动器，因此只能使用“大标题提醒你装Optifine”的方法。光影和配置应该是可以发布的，但是只有安装了Optifine才有效果。

**Comment by ZYLHL** [comment]
我可以为Curseforge的发布工作贡献一份力。有什么需求email我。
