### ISSUE TITLE
[Suggestion] 关于天地宝晶合成材料生成问题

### ISSUE THREAD

**Issue by ylq2711960454** [TCreopargh/GreedyCraft#55]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
天地宝晶合成的材料有几种不生成，分别是：坦桑石，孔雀石，黄玉，橄榄石，紫水晶（已解决）
我和我朋友连着挖了五天（现实世界的五天），各种地形,群系，全部去过，但是没有找到一种上述的矿石
紫水晶这个矿石在末地不生成，我和我朋友几乎把末影龙所在的那个大岛挖空也没见到一个紫水晶，在末地的其他地方也去挖过，均未发现，但是地狱有一种紫水晶和它的矿物辞典一样，所以就用地狱那个紫水晶替代了末地的紫水晶

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.19.1
 * Java版本：1.8.0_161 64位
 * 分配的内存：16G
 * 物理内存：24G
 * 是否增减了mod：是
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：是
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.19.1
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
所有宝石均可生成，请查看mcmod的wiki。注意在阶段hardmode之前所有宝石都会伪装成石头/末地石。

**Comment by ylq2711960454** [comment]
我和我朋友是在造炫钢锭的时候去找的天地宝晶，前两天是我在找，主世界,漆黑世界，都找过，但是也只是找到了红宝石蓝宝石，绯红宝石和琥珀，后几天是我朋友找的，他是根据的mcmod给出的群系找的，但也是一无所获，就卡阶段卡在了炫钢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TCreopargh/GreedyCraft"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 下午4:46
收件人:&nbsp;"TCreopargh/GreedyCraft"<GreedyCraft@noreply.github.com&gt;;
抄送:&nbsp;"2711960454"<2711960454@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TCreopargh/GreedyCraft] [Suggestion] 关于天地宝晶合成材料生成问题 (#55)





 
所有宝石均可生成，请查看mcmod的wiki。注意在阶段hardmode之前所有宝石都会伪装成石头/末地石。

**Comment by TCreopargh** [comment]
有些可能需要原版群系，这样吧，我下次更新额外加一些宝石生成并且加一个混合各种宝石但是很稀有的矿脉，应该能解决问题
