### ISSUE TITLE
[BUG] 猝死

### ISSUE THREAD

**Issue by Pekton** [TCreopargh/GreedyCraft#56]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
本地局域网环境，联机小伙伴，服主无此bug。
在一定深度之下(40)，在特定位置走两步会突然猝死，无怪物，无水（感觉需要在水下环境，地牢或者海底挖下去会死，洞穴没有完整测试，但是好像没事）。

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

[20:05:24] [Server thread/INFO] [OpenMods]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:304): Storing post-mortem inventory into E:\GreedyCraft-1.22.1\.minecraft\versions\GreedyCraft\saves\Backup--Brave New World--2021-01-06--20-09\data\inventory-Pekton-2021-01-07_20.05.24-death-0.dat. It can be restored with command '/ob_inventory restore Pekton Pekton-2021-01-07_20.05.24-death-0'
[20:05:24] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: 标题命令执行成功
[20:05:24] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: 标题命令执行成功
[20:05:24] [Client thread/INFO] [de.keksuccino.biggerchathistory.CustomChatGui]: [CHAT] §c? §7§ePekton§7§7淹死了§7 §9@ §7(§3-6738§7, §339§7, §34959§7)

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1.
![2021-01-07 (3)](https://user-images.githubusercontent.com/17193981/103937532-261ee500-5129-11eb-8eb3-bddf88421e7a.png)
![image](https://user-images.githubusercontent.com/17193981/103936680-0509c480-5128-11eb-9587-0746fdbada47.png)
就这么往前走就死了

2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.22.1
 * Java版本：java version "1.8.0_271"
 * 分配的内存：服主16240MB，联机10240MB
 * 物理内存：24GB，16GB
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：更新两次
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

PS：又遇到一次waiting for server，stall报告在这里：[stall-2021-01-07_20.06.29](https://paste.ubuntu.com/p/PXFVgNrxWR/)
[latest.log](https://paste.ubuntu.com/p/7yNBJpQCHd/)

**Comment by mavqwq** [comment]
有水下呼吸效果就不会死，可以做水下药去新生成的海底挖几个水华矿，做盔甲部件或者泡泡指环提供无限的水下呼吸

**Comment by Pekton** [comment]
> 有水下呼吸效果就不会死，可以做水下药去新生成的海底挖几个水华矿，做盔甲部件或者泡泡指环提供无限的水下呼吸

我认为这是个bug是因为这个地牢入口本身在陆地上，然后延伸到海水中。而且地牢内的空间本身是自然产生的而并非利用火把等机制生成的，我认为在地牢中探险需要水下呼吸是不合理的。

**Comment by mavqwq** [comment]
我是1.9.1老版本更新的，家就在海边，当时的自然生成矿洞是不会填充水的，导致我们更新后下矿第一时间就发现了会淹死。具体是只要在海洋群系地下，在空气里就会受到大概100点真伤一次的不间断伤害。我翻看更新日志发现1.14你更新条目里有无法使用火把大法呼吸，应该是这机制引起的。additions这模组作者自己写的，这是代码杀，没办法。ps:空气里淹死确实挺离谱，水里反而能撑更久，暴露在空气里直接被秒。

**Comment by TCreopargh** [comment]
我试试优化下判定，如果周围所有方块都是空气就不扣血

**Comment by Pekton** [comment]
> 我试试优化下判定，如果周围所有方块都是空气就不扣血

一个人周围有26个方块，地牢里面有的时候会有点水漏进来，我建议设定一个类似于超过多少个方块是水的判定，不然的话就可能会出现类似于在地牢里趟水过去就猝死的情况。

**Comment by Pekton** [comment]
> 我试试优化下判定，如果周围所有方块都是空气就不扣血

另外我今天发现在该地牢中低于40的位置敲掉一个方块就会生成一格水，这符合在水底挖东西的情况，但是似乎不太适合一个地牢？

**Comment by TCreopargh** [comment]
这样吧，我尽可能让地牢不在海底生成就可以了

**Comment by TCreopargh** [comment]
似乎你所说的地牢并没有根据生物群系决定是否生成的功能。并且我仔细想了下，增大空气判定范围可能导致更多的bug（比如如果是实体方块占周围绝大多数应该怎么做，以及处于海沟里之类的情况）为了避免造成更多bug，我只能建议你用水下呼吸药水再探索地牢或者干脆不要探索海底的地牢。
