### ISSUE TITLE
[BUG] 使用杂酚油崩溃

### ISSUE THREAD

**Issue by sqdxiucai** [TCreopargh/GreedyCraft#59]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
使用ThermalFoundation时杂酚油崩溃，无论是桶装杂酚油还是大桶杂酚油，倒在地上或放在容器，或放在发电机发电都会崩溃，弹出崩溃界面

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
崩溃报告:https://paste.ubuntu.com/p/Rfd2M47hKN/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 倒在地上或放在容器，或放在发电机发
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：
 * Java版本：
 * 分配的内存：
 * 物理内存：
 * 是否增减了mod：
 * 是否修改了材质包：
 * 是否修改了魔改/配置文件：
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
已向CQR反馈
https://github.com/TeamChocoQuest/ChocolateQuestRepoured/issues/241

**Comment by sqdxiucai** [comment]
> # 贪婪整合包 Bug反馈表
> **注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
> 此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。
> 
> ## 请在下面详细描述你遇到的Bug
> bug描述
> 使用ThermalFoundation时杂酚油崩溃，无论是桶装杂酚油还是大桶杂酚油，倒在地上或放在容器，或放在发电机发电都会崩溃，弹出崩溃界面
> 
> ## 如果Bug造成了崩溃，请将崩溃报告的链接粘贴在下面
> ### 崩溃报告位于整合包根目录的crash-reports文件夹下，文件名为发生崩溃时的时间。请不要把崩溃报告整个粘贴在下面！请使用在线剪贴板软件（如： https://paste.ubuntu.com/ ）将崩溃报告复制进contents里，Poster填你的名字，然后按Paste，把点击后打开的网页的地址粘贴到下面。
> ### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）
> 崩溃报告/日志地址
> 崩溃报告:https://paste.ubuntu.com/p/Rfd2M47hKN/
> 
> ## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
> 1. 倒在地上或放在容器，或放在发电机发
> 
> ## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
> * 整合包版本：1.23.0
> * Java版本：Java8   271
> * 分配的内存：10240MB
> * 物理内存：16G
> * 是否增减了mod：否
> * 是否修改了材质包：否
> * 是否修改了魔改/配置文件：否
> * 使用的光影（如果不是渲染问题可以不填）：
> * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
> * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.21.1
> 
> ## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。
> 解决方法

**Comment by TCreopargh** [comment]
巧克力地牢已更新，请自行将ChocolateQuestRepoured升级到2.2.2以解决该问题，整合包下版本才会实装该更新

**Comment by TCreopargh** [comment]
1.25.0已修复
