### ISSUE TITLE
[BUG] 在jei内拿出富集泥炭会导致游戏崩溃

### ISSUE THREAD

**Issue by superDXZ** [TCreopargh/GreedyCraft#6]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
在jei内拿出富集泥炭会导致游戏崩溃

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
https://paste.ubuntu.com/p/kWTSkS59hH/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 在jei内拿出富集泥炭会导致游戏崩溃（开jei作弊模式）
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：GreedyCraft-1.14.1
 * Java版本：jre-8u271-windows-x64
 * 分配的内存：6.5G(6646M)
 * 物理内存：8G
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
经测试并没有发生崩溃，请你重启下游戏看看还会不会崩？

**Comment by superDXZ** [comment]
不会了，谢谢花姐
