### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AlexKear** [TCreopargh/GreedyCraft#62]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
游戏版本更新存档转移后进入地图加载区块加载一会后会显示一句CCL Caught an exception rendering a block .See the log for info.然后游戏就会卡死不动，等过20分钟也没有反应。只能强制关闭。每次进入存档区块只加载了一点时还能动，一会后就会卡住或者会崩溃，尝试过多次。

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
https://paste.ubuntu.com/p/77kP8pjKyT/

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.23.0
 * Java版本：
 * 分配的内存：10240
 * 物理内存：16g
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：amd 4800h rtx2060
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 更新后出现的问题
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
是更多使用设备2消音器导致的问题，请试下移除该方块看看有没有解决

**Comment by TCreopargh** [comment]
1.24.0应该已经修复

**Comment by AlexKear** [comment]
1.24.0存档打开没问题，但依旧会出现waiting for server…
