### ISSUE TITLE
[BUG] 还是谜一样的崩溃

### ISSUE THREAD

**Issue by binglingyao** [TCreopargh/GreedyCraft#63]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
1.副手手持匠魂工具,使用快捷栏的无线合成重点饰品打开AE，按下ESC后崩溃
2.在雪地并且在主世界末地要塞上方,会导致掉帧到0~3fps.(无论是否开关光影),平时帧数110~160.
3.在某些情况下会导致突然崩溃(进入存档即刻崩溃,再次进入有可能恢复),这项在重启游戏后依然存在

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址
[crash-2021-01-11_00.19.34-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5792902/crash-2021-01-11_00.19.34-client.txt)

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本： 1.23.0
 * Java版本：8_271
 * 分配的内存：20G
 * 物理内存：32G
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：修改了联机MOD的config,具体为正版验证和端口
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：显卡: 公版2060 CPU: i7-7800
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）1.22.3fix(随后跟随每一个版本更新)
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by binglingyao** [comment]
补充崩溃日志
1.
[crash-2021-01-10_22.27.27-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5792910/crash-2021-01-10_22.27.27-client.txt)
2.
[crash-2021-01-10_22.25.21-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5792911/crash-2021-01-10_22.25.21-client.txt)
3.
[crash-2021-01-10_22.23.19-client.txt](https://github.com/TCreopargh/GreedyCraft/files/5792912/crash-2021-01-10_22.23.19-client.txt)

**Comment by TCreopargh** [comment]
最新版似乎已经修复了
