### ISSUE TITLE
[BUG] 1.25.0怪物大面积当面凭空消失

### ISSUE THREAD

**Issue by binglingyao** [TCreopargh/GreedyCraft#73]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述:

出去砍怪,一群怪物当着我面人间蒸发了!还有的怪砍到一半没了!
好像很早以前就有这个毛病(大约1.17.X,我以为是正常现象,最早是从修格斯身上发现的，当着我面8只消失得只剩下2只)
现在大面积的出现这种情况就不对劲了

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.25.0
 * Java版本：8_271
 * 分配的内存：16G
 * 物理内存：32G
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：是
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
请详细描述下是哪种怪物
怪物有自动清除机制，为了防止卡顿系统每隔一段时间会搜索所有生物，如果一种生物超过了一定数量就会清除到规定的数量，这是为了防止卡顿。

**Comment by binglingyao** [comment]
最常在我面前消失的是骷髅,其次是修格斯(修格斯才6~7个啊!)
僵尸和苦力怕以及蜘蛛都很少(没注意,至少不会像前两个一样)消失
顺带骷髅消失了会留下一地的骷髅马...

**Comment by binglingyao** [comment]
我似乎还没见过女巫消失

**Comment by binglingyao** [comment]
嗯...消失最常见的地方是在主世界

**Comment by binglingyao** [comment]
以及如果是在和别人联机（非自己做主机）这会非常频繁

**Comment by TCreopargh** [comment]
1.25.1已修复
