### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by binglingyao** [TCreopargh/GreedyCraft#78]
## 描述你的想法或建议
原因在于AE,当你单人的时候跨世界因为区块被卸载了 无 法 打 开
于是就有了这个想法!

**Comment by TCreopargh** [comment]
请描述下你的建议是什么？

**Comment by binglingyao** [comment]
增加一个区块加载器

**Comment by binglingyao** [comment]
这里举个例子,如Railcraft[铁路]的区块加载器

**Comment by TCreopargh** [comment]
已经有了，都不看的吗，仔细看书。。。ftb的声明区块也可以设成加载
