### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zjh790** [TCreopargh/GreedyCraft#8]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug
1.从较低版本直接跟新到最新版后阶段与任务重置，即任务白干，但是可以领取，阶段完全重置（离线登录，从1.12.2更新，之前倒回过版本）
2.玩久了之后，可能会有物品看不见，尤其是半透明以及透明的东西（有时可以通过去其他维度解决）（当然以前不开光影也是这样的,当然也有可能是显卡不行（20帧不到家中））

bug描述

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.15.0
 * Java版本：忘记了，但是其他版本正常
 * 分配的内存：10240
 * 物理内存：512G（应该是这玩意吧，还是16G那个？）
 * 是否增减了mod：无
 * 是否修改了材质包：无
 * 是否修改了魔改/配置文件：无
 * 使用的光影（如果不是渲染问题可以不填）：默认
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：AMD r5 4600H,AMD Radeon(TM) Graphics
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：只记得应该在1.10.0之前了吧，频繁更新的
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
1是uuid改变的问题，请复制hmcl.json过来，如果还是没法解决请考虑购买正版或外置登录
2应该可以通过关闭顶点缓冲器解决（视频设置里找）

**Comment by zjh790** [comment]
https://paste.ubuntu.com/p/xW7NyHfSjH/, 之前用过外置登录，一样的结果，然后回档了
