### ISSUE TITLE
mod添加建议 

### ISSUE THREAD

**Issue by CiQiu124** [TCreopargh/GreedyCraft#86]
## 描述你的想法或建议
最近偶然看到一个mod：GuGu Utils
其中该mod对植物魔法的修改可以提高玩家的游戏体验
mcbbs原贴：https://www.mcbbs.net/thread-1150397-1-2.html
mod功能可参照原贴
不过多赘述
## 你是否有实现该想法的方法或建议？如果有，请说明
该mod的模块化机械附属也可以增加模块化机械的多样性
让玩家不单纯的做好一个机械摆在家里就ok了 而是在其中加入一些探险元素
以及该mod对于JEI的支持也可以提高部分玩家体验 不需要繁琐的去操作
植物魔法支持的A.D条的改动也可以让玩家的体验提高 超频透镜也是一种减少制作魔力奇点的时间好办法
对火红莲的改动也可以让玩家的产魔不拘泥于火红莲阵列 而去探索一些别样的 更有趣的产魔方法 
以上皆为个人想法

**Comment by TCreopargh** [comment]
为了能发布至curseforge，该模组也必须发布至curseforge，否则无法国际化。
