### ISSUE TITLE
[BUG] 匠魂盔甲在耐久度充足的情况下受击突然消失

### ISSUE THREAD

**Issue by gomamon282** [TCreopargh/GreedyCraft#91]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
匠魂盔甲只要安装了电容就能触发最后防线。
匠魂盔甲会在耐久充足的情况下突然消失，在此场合下均有精英怪在场，疑似是某精英怪特性导致。
盔甲配置:胞嘧头盔基底 云浮护甲夹板 信素护甲板
耐钢胸甲基底 云浮护甲夹板 信素护甲板
耐钢胸甲基底 陨星护甲夹板 史莱姆骑士护甲板
胞嘧鞋子基底 星辰护甲夹板 铂护甲板
无论是否安装了电容升级均存在突然消失的情况，安装电容升级时似乎会在触发了两到三次最后防线后突然消失。
### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.26.0
 * Java版本：Java8 64位
 * 分配的内存：11240 M
 * 物理内存：16 G
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：星辉魔法星能力等级上限调至100
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：是
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by gomamon282** [comment]
Java版本为jre1.8.0_181

**Comment by TCreopargh** [comment]
应该已经修复
