### ISSUE TITLE
树叶透视

### ISSUE THREAD

**Issue by DZX66** [TCreopargh/GreedyCraft#96]
进入树叶看地下有透视效果
![Snipaste_2021-02-02_10-16-39](https://user-images.githubusercontent.com/76642827/106542976-ceb14080-653f-11eb-8f3e-5e072f45fa2e.png)

**Comment by TCreopargh** [comment]
请关闭顶点缓冲器和区域渲染

**Comment by TCreopargh** [comment]
请勿使用流畅设置
不会解决此类问题
