### ISSUE TITLE
[BUG] 钓鱼竿和自动鱼栅

### ISSUE THREAD

**Issue by ylq2711960454** [TCreopargh/GreedyCraft#97]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
用一个无限耐久的钓鱼竿（有紫色单词介绍的钓鱼竿）和自动鱼栅可以一次钓上来64个物品（药水居多，但是实用的物品也不少，比如：各种矿物，心粉，催化之星，荣誉之板，奖励袋以及奖励箱等等）。有图但是我用的手机所以发不出来，明天再发物品截图以及钓鱼竿信息和具体结构摆放
附：这个钓鱼竿可以在生成海盗的那个地牢的箱子里获得
另外还有一个bug。。。
是关于四倍矿物的，整个四倍矿做出来后，我们发现大部分矿物在经过最后一步的时候，输出出来会是64个物品（就是把锭磨成粉再放进去那个机器。矿物很多，而且比较重要或者重要的矿物基本都可以被64倍输出出来，比如：钛金，永然，咆嘧，极寒，飞龙金属锭，神龙金属锭等等，附：因为我们还没玩到混沌，所以不清楚混沌金属锭可不可以64倍矿）。结构截图明天发，因为时间太晚了，见谅。

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 明天我会发给你详细的结构摆放以及各个部件名称
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：1.25.1
 * Java版本：64喂
 * 分配的内存：16g
 * 物理内存：24g
 * 是否增减了mod：是
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：是
 * 使用的光影（如果不是渲染问题可以不填）：
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。

解决方法

**Comment by TCreopargh** [comment]
请删除你自己加的终极堆叠mod
