### ISSUE TITLE
[BUG] 偶发在某种情况下某些朝向树叶和草地异常的渲染为透明

### ISSUE THREAD

**Issue by CafuChino** [TCreopargh/GreedyCraft#98]
# 贪婪整合包 Bug反馈表
**注意：不接收有关安装问题和内存问题的Bug反馈。**（即：如果游戏毫无征兆的突然崩溃（没有显示VanillaFix的崩溃信息界面），或者你在安装时遇到了问题，请勿提交为Bug。）请参考安装教程（ https://greedycraft.tcreopargh.xyz/?p=258 ）进行修复。
此表仅用于反馈Bug。如果你想提交一个建议，你可以仍然在GitHub的issues页面提交，但请勿参照此表填写。

## 请在下面详细描述你遇到的Bug

bug描述
如图，在主世界和暮色森林都有偶发，转动视角可以在某些视角下恢复正常显示，但是一转到某些视角便会出现此现象
![image](https://user-images.githubusercontent.com/49181984/106914492-f8639680-66fc-11eb-9c24-62abf12f6777.png)
重新进入存档问题依然会触发
重新进入游戏依然会触发
升级过游戏依然会触发

### 如果没你觉得提供日志有助于解决该问题，可以把logs文件夹里的日志地址粘贴到下面：（最新的日志是latest.txt，之前的日志需要解压）

崩溃报告/日志地址

## 如果你有方法重现这个Bug（即：有固定的方法让Bug发生），请在下面详细说明：
1. 
2. 
3. 

## 发生bug时你的配置信息：（如果整合包版本不是最新建议更新再试）
 * 整合包版本：GreedyCraft-1.29.0.104.0
 * Java版本：JDK 1.8.0_271
 * 分配的内存：10G 
 * 物理内存：16G
 * 是否增减了mod：否
 * 是否修改了材质包：否
 * 是否修改了魔改/配置文件：否
 * 使用的光影（如果不是渲染问题可以不填）：默认
 * CPU及显卡型号（如果不是渲染/低FPS问题可以不填）：i7 10700 蓝宝石白金5500xt
 * 创建世界时的版本（如果不记得可以只填是否在使用这个世界的过程中更新了版本）：1.26.0
 
## 如果你有解决该Bug的方法或者建议可以写在下面，如果没有可以不填。
怀疑可能与BetterFoliage模组有关系，因为仅草方块或叶子会异常渲染，在F8中关闭模组并不会解决这个问题。正在尝试临时删除模组测试
解决方法

**Comment by TCreopargh** [comment]
请更新显卡驱动
如果还是没用请关闭顶点缓冲器
